import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('Organization chat protects backend evidence, tenant isolation, quotas and lifecycle stop',async()=>{
 const db=new PGlite();
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',v='33333333-3333-4333-8333-333333333333';
 const oa='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',ob='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',conversation='44444444-4444-4444-8444-444444444444',request='55555555-5555-4555-8555-555555555555';
 try{
 await db.exec(`create schema auth;create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,deleted_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated,service_role;grant execute on function auth.uid() to authenticated,service_role;
 insert into auth.users values ('${a}','a@example.test',now(),null),('${b}','b@example.test',now(),null),('${v}','v@example.test',now(),null);`);
 for(const name of ['202609250001_core.sql','20260928004208_education_agent.sql','20260928083927_business_agent.sql','20260928123000_business_agent_channels_approvals.sql','20260928124000_business_agent_fk_indexes.sql','20260928181514_public_platform.sql','20260928181706_action_approval_guard.sql','20260928182818_action_ledger_triggers.sql'])await db.exec(await readFile('supabase/migrations/'+name,'utf8'));
 await db.exec(`create schema private;
 create table organizations(id uuid primary key,owner_id uuid,name text not null,slug text not null);
 create table organization_members(organization_id uuid references organizations,user_id uuid,role text,primary key(organization_id,user_id));
 create table agent_installations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,name text not null default 'KOWI',status text not null default 'draft' constraint agent_installations_status_check check(status in ('draft','active','paused')),config jsonb not null default '{}',allowed_origins text[] not null default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
 insert into organizations values ('${oa}','${a}','A','a'),('${ob}','${b}','B','b');
 insert into organization_members values ('${oa}','${v}','viewer');
 grant usage on schema private to service_role;`);
 await db.exec(await readFile('supabase/migrations/20261003000200_universal_tenant_crm.sql','utf8'));
 await db.exec(`alter table agent_installations enable row level security;grant select,insert,update on agent_installations to authenticated;grant all on agent_installations to service_role;grant all on conversations,agent_ledger to service_role;
 create policy install_read on agent_installations for select to authenticated using(private.crm_role(organization_id) is not null);
 create policy install_write on agent_installations for all to authenticated using(private.crm_role(organization_id) in ('owner','admin','configurator')) with check(private.crm_role(organization_id) in ('owner','admin','configurator'));`);
 await db.exec(await readFile('supabase/migrations/20261003000500_agent_lifecycle.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20261003000800_organization_chat.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20261003000900_conversation_crm_capture.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20261003001000_agent_jobs.sql','utf8'));
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
 const agent=(await db.query<{id:string}>('insert into agent_installations(organization_id) values ($1) returning id',[oa])).rows[0].id;
 await assert.rejects(db.query("insert into agent_installations(organization_id,status) values ($1,'active')",[oa]),/must start in draft/);
 await assert.rejects(db.query("update agent_installations set status='active' where id=$1",[agent]),/Verify/);
 await assert.rejects(db.query('update agent_installations set last_verified_at=now()'),/permission denied/);
 await assert.rejects(db.query('select consume_organization_ai_quota($1,$2)',[oa,a]),/permission denied/);
 await db.exec('reset role;set role service_role');
 const begin='select begin_organization_chat_job($1,$2,$3,$4,$5)';
 const second='88888888-8888-4888-8888-888888888888',third='99999999-9999-4999-8999-999999999999';
 await db.query(begin,[oa,agent,a,request,'a'.repeat(64)]);
 await db.query(begin,[oa,agent,a,second,'b'.repeat(64)]);
 await db.query(begin,[oa,agent,a,third,'c'.repeat(64)]);
 await assert.rejects(db.query(begin,[oa,agent,a,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','d'.repeat(64)]),/concurrency limit/);
 await db.query('select fail_organization_chat_job($1,$2,$3)',[oa,a,second]);
 await db.query('select fail_organization_chat_job($1,$2,$3)',[oa,a,third]);
 await db.query(begin,[oa,agent,a,second,'b'.repeat(64)]);
 await db.query('select fail_organization_chat_job($1,$2,$3)',[oa,a,second]);
 await assert.rejects(db.query(begin,[oa,agent,a,second,'b'.repeat(64)]),/cannot be restarted/);
 await db.query(begin,[oa,agent,a,third,'c'.repeat(64)]);
 await db.query("update agent_actions set attempt_started_at=now()-interval '2 minutes' where job_id=$1",[third]);
 assert.equal((await db.query<{expire_organization_agent_jobs:number}>('select private.expire_organization_agent_jobs()')).rows[0].expire_organization_agent_jobs,1);
 const updated=(await db.query<{updated:string}>('select updated_at::text updated from agent_installations where id=$1',[agent])).rows[0].updated;
 const save='select save_organization_chat($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)';
 const args=[oa,agent,a,conversation,request,0,'Pregunta sintética de test','Respuesta sintética de test','test-model',30,4,'test-provider-id',updated];
 await assert.rejects(db.query(save,[...args.slice(0,2),b,...args.slice(3)]),/insufficient_privilege/);
 await db.query(save,args);
 await assert.rejects(db.query(save,args),/changed/);
 for(let i=0;i<12;i++)assert.equal((await db.query<{consume_organization_ai_quota:boolean}>('select consume_organization_ai_quota($1,$2)',[oa,a])).rows[0].consume_organization_ai_quota,true);
 assert.equal((await db.query<{consume_organization_ai_quota:boolean}>('select consume_organization_ai_quota($1,$2)',[oa,a])).rows[0].consume_organization_ai_quota,false);
 await db.exec('reset role;set role authenticated');
 assert.equal((await db.query('select * from messages')).rows.length,2);
 const metrics=(await db.query<{prompt_tokens:number;completion_tokens:number;ai_spend:null}>('select * from agent_metrics')).rows[0];
 assert.equal(metrics.prompt_tokens,30);assert.equal(metrics.completion_tokens,4);assert.equal(metrics.ai_spend,null);
 await assert.rejects(db.query("insert into messages(organization_id,conversation_id,request_id,sequence,role,content) values ($1,$2,gen_random_uuid(),2,'assistant','Forged')",[oa,conversation]),/permission denied/);
 await assert.rejects(db.query("select save_chat_turn($1,gen_random_uuid(),0,'Forged','Forged',null)",[conversation]),/insufficient_privilege/);
 await assert.rejects(db.query("insert into agent_ledger(actor_id,organization_id,agent,action,permission,result) values ($1,$2,'business','forged','owner','completed')",[a,oa]),/row-level security/);
 await db.query("update agent_installations set status='active' where id=$1",[agent]);
 await db.exec('reset role;set role service_role');
 await db.query(begin,[oa,agent,a,'66666666-6666-4666-8666-666666666666','e'.repeat(64)]);
 await db.exec('reset role;set role authenticated');
 await db.query("update agent_installations set status='paused' where id=$1",[agent]);
 assert.equal((await db.query<{status:string}>("select status from agent_actions where job_id='66666666-6666-4666-8666-666666666666'")).rows[0].status,'cancelled');
 await assert.rejects(db.query('delete from agent_job_events'),/permission denied/);
 await db.exec('reset role;set role service_role');
 await assert.rejects(db.query(save,[...args.slice(0,4),'66666666-6666-4666-8666-666666666666',1,...args.slice(6)]),/Agent unavailable/);
 await db.exec('reset role;set role authenticated');
 await db.query("update agent_installations set status='revoked' where id=$1",[agent]);
 await db.query("update agent_installations set status='terminated' where id=$1",[agent]);
 assert.equal((await db.query('select * from messages')).rows.length,2);
 await db.exec('reset role;set role service_role');
 const capture='select capture_organization_conversation($1,$2,$3,$4,$5,$6,$7,$8,$9)';
 const captureArgs=[oa,a,conversation,'77777777-7777-4777-8777-777777777777','Contacto sintético de test','fixture@example.test','',false,'Oportunidad sintética de test'];
 const captured=(await db.query<{capture_organization_conversation:{contactId:string;leadId:string;opportunityId:string}}>(capture,captureArgs)).rows[0].capture_organization_conversation;
 const replay=(await db.query<{capture_organization_conversation:{contactId:string}}>(capture,captureArgs)).rows[0].capture_organization_conversation;
 assert.equal(replay.contactId,captured.contactId);
 await assert.rejects(db.query(capture,[...captureArgs.slice(0,8),'Otro título']),/request reused/);
 await assert.rejects(db.query(capture,[oa,b,...captureArgs.slice(2)]),/insufficient_privilege/);
 await assert.rejects(db.query(capture,[ob,b,...captureArgs.slice(2)]),/conversation unavailable/);
 await assert.rejects(db.query(capture,[oa,v,...captureArgs.slice(2)]),/insufficient_privilege/);
 await db.exec('reset role;set role authenticated');
 assert.equal((await db.query('select * from contacts')).rows.length,1);
 assert.equal((await db.query('select * from leads')).rows.length,1);
 assert.equal((await db.query('select * from opportunities')).rows.length,1);
 await db.query('insert into tasks(organization_id,title,opportunity_id) values ($1,$2,$3)',[oa,'Seguimiento sintético',captured.opportunityId]);
 await assert.rejects(db.query('select * from private.conversation_capture_requests'),/permission denied/);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);
 assert.equal((await db.query('select * from messages')).rows.length,0);
 assert.equal((await db.query('select * from agent_metrics')).rows.length,0);
 assert.equal((await db.query('select * from agent_actions')).rows.length,0);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[v]);
 assert.equal((await db.query('select * from messages')).rows.length,2);
 await assert.rejects(db.query(save,args),/permission denied/);
 }finally{await db.close();}
});
