import type { Metadata } from 'next';
import Link from 'next/link';
import { agentById } from '@/lib/agents/registry';

export const metadata: Metadata = {
  title: 'Espacios para aprender y cuidar | Iniciativa de impacto KOWI',
  description: 'Modelo propuesto para desarrollar escuelas, universidades y centros de salud con acceso gratuito, inversión responsable, operación y posible transferencia pública.',
};

const spaces = [
  { name: 'Escuelas presenciales', purpose: 'Aprender en comunidad, con docentes, herramientas y espacios seguros. La educación digital complementa la experiencia humana.', condition: 'Proyecto pedagógico, equipo, terreno, licencias y autoridad educativa competente.' },
  { name: 'Universidades y formación superior', purpose: 'Investigar y formar profesionales que puedan resolver problemas reales y compartir conocimiento.', condition: 'Viabilidad académica, autorización y acreditación aplicables; no se ofrecen títulos desde KOWI.' },
  { name: 'Centros de salud', purpose: 'Acercar prevención, orientación y atención profesional a comunidades con necesidades identificadas.', condition: 'Personal sanitario, habilitaciones, protección de datos y coordinación con el sistema público.' },
  { name: 'Hospitales', purpose: 'Explorar infraestructura asistencial donde la necesidad, la capacidad de operación y la alianza pública lo justifiquen.', condition: 'Evaluación clínica y territorial, financiación sostenida, autorización y gobierno sanitario independiente.' },
];

const phases = [
  { number: '01', title: 'Escuchar y elegir', work: 'La comunidad y profesionales identifican una necesidad concreta, población, lugar y capacidad requerida.', gate: 'El consejo promotor valida el propósito y autoriza solo el estudio de viabilidad.' },
  { number: '02', title: 'Estudiar la viabilidad', work: 'Analizar demanda, terreno o derecho de uso, permisos, impacto, riesgos, alternativas y acuerdo preliminar con la autoridad competente.', gate: 'Consejo técnico independiente y socios promotores revisan el estudio antes de diseñar.' },
  { number: '03', title: 'Diseñar y financiar', work: 'Proyecto arquitectónico y de servicio, presupuesto verificable, fuentes de capital, operación a largo plazo, reservas y modelo de acceso sin cobro.', gate: 'No comprometer obra ni anunciar plazas sin financiación, permisos y aprobaciones documentadas.' },
  { number: '04', title: 'Construir y equipar', work: 'Contratación, dirección profesional, controles de calidad, seguridad, hitos de obra, equipamiento y auditoría de costes.', gate: 'Pagos y cambios materiales requieren aprobación humana, evidencia y trazabilidad.' },
  { number: '05', title: 'Abrir con garantías', work: 'Recepción de obra, habilitaciones, contratación de equipos, pruebas operativas y apertura gradual según capacidad.', gate: 'Solo se declara terminado cuando se entregan obra, documentación, equipos y permisos de operación.' },
  { number: '06', title: 'Operar y mejorar', work: 'Horizonte propuesto de 30 años desde la entrega de obra: administración responsable, mantenimiento y mejora anual con informes públicos.', gate: 'Cada año se revisan resultados, acceso, seguridad, presupuesto y necesidades de reinversión.' },
  { number: '07', title: 'Transferir si se acuerda', work: 'Preparar con antelación una eventual entrega al gobierno competente: estado de activos, obligaciones, continuidad del servicio y aceptación formal.', gate: 'La transferencia solo ocurre bajo un instrumento válido y con aceptación de la Administración.' },
];

const funds = [
  { label: 'Preparación', detail: 'Diagnóstico, estudios, participación comunitaria, asesoría y derechos sobre el lugar.' },
  { label: 'Inversión de obra', detail: 'Diseño, permisos, construcción, equipamiento, puesta en marcha y contingencia.' },
  { label: 'Operación', detail: 'Personal, suministros, mantenimiento, materiales, seguros y revisión profesional.' },
  { label: 'Mejora y continuidad', detail: 'Reserva anual para reparación, actualización, accesibilidad e innovación durante la operación.' },
];

const decisionRecord = [
  { moment: 'Antes de comprometer capital', evidence: 'Necesidad medida, alternativas, suelo o derecho de uso, estimación de inversión y costes anuales, fuentes de financiación y riesgos.', decision: 'Socios promotores autorizan el alcance y el presupuesto del diseño; especialistas revisan la viabilidad.' },
  { moment: 'Antes de contratar la obra', evidence: 'Diseño profesional, permisos exigibles, presupuesto de obra con contingencias, plan de contratación y financiación de construcción y operación.', decision: 'Aprobación humana documentada del órgano competente; contratos sujetos a la estructura jurídica y controles aplicables.' },
  { moment: 'Antes de atender personas', evidence: 'Recepción de obra, autorizaciones, personal habilitado, equipamiento probado, pólizas y plan de seguridad y continuidad.', decision: 'La dirección profesional y las autoridades competentes autorizan la apertura según sus atribuciones.' },
  { moment: 'Durante los 30 años propuestos', evidence: 'Informes anuales de acceso, calidad, mantenimiento, incidentes, uso de reservas y presupuesto del siguiente año.', decision: 'Órgano de gobierno aprueba mejoras y reinversión; revisión independiente de resultados y cuentas.' },
  { moment: 'Antes de una eventual transferencia', evidence: 'Inventario, estado técnico y jurídico, obligaciones laborales y contractuales, financiación pendiente y plan de continuidad.', decision: 'Acuerdo válido y aceptación expresa del gobierno competente; sin ello no se anuncia ni ejecuta entrega.' },
];

const infrastructureAgent = agentById('foundation-infrastructure');

export default function FoundationInfrastructure() {
  return <main className="kowi-cosmos min-h-screen">
    <header className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-7 md:px-10"><Link href="/fundacion" className="inline-flex items-center gap-3 text-[#e8b37b]"><span className="kowi-emblem" aria-hidden="true"/><span className="font-semibold tracking-[.28em]">KOWI</span></Link><Link href="/fundacion" className="text-sm text-[#c6c9d0]">← Volver a la iniciativa</Link></header>
    <section className="border-y border-white/10 bg-[radial-gradient(circle_at_75%_25%,#b57b4b25,transparent_38%),linear-gradient(130deg,#142339,#060b16_65%)] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">MISIÓN A LARGO PLAZO · PROPUESTA EN ESTUDIO</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.08] tracking-tight md:text-7xl">Lugares reales para <span className="text-[#e8b37b]">aprender y cuidar.</span></h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-[#c5cad3]">Queremos que la misión de KOWI llegue más allá de una pantalla: escuelas, universidades, centros de salud y hospitales construidos con personas y profesionales. Aspiramos a que quienes puedan acceder lo hagan sin pagar por el servicio, con financiación sostenible y criterios de acceso justos.</p><p className="mt-5 max-w-3xl text-sm leading-relaxed text-[#aeb6c4]">Esta es una visión y un método propuesto. No hay centros construidos, plazas disponibles, proyectos financiados ni acuerdos de transferencia anunciados por esta iniciativa.</p><a href="#fases" className="mt-8 inline-flex rounded-full border border-white/30 px-6 py-3">Conocer el modelo ↓</a></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:px-10"><p className="kowi-eyebrow">CUATRO FORMAS DE SERVIR</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold">La infraestructura sigue a una necesidad humana.</h2><div className="mt-9 grid gap-4 md:grid-cols-2">{spaces.map((space) => <article key={space.name} className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">{space.name}</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">{space.purpose}</p><p className="mt-5 border-t border-white/10 pt-4 text-sm text-[#aeb6c4]">Antes de abrir: {space.condition}</p></article>)}</div></section>
    <section id="fases" className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">DE LA IDEA A LA ENTREGA</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold">Siete fases. Una decisión documentada antes de avanzar.</h2><div className="mt-9 grid gap-4 md:grid-cols-2">{phases.map((phase) => <article key={phase.number} className="cosmos-panel rounded-2xl p-6"><span className="text-sm text-[#e8b37b]">{phase.number} / FASE</span><h3 className="mt-4 text-xl font-semibold">{phase.title}</h3><p className="mt-3 leading-relaxed text-[#bdc4cf]">{phase.work}</p><p className="mt-5 border-t border-white/10 pt-4 text-sm text-[#e5cfb9]">Puerta de aprobación: {phase.gate}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[.85fr_1.15fr] md:px-10"><div><p className="kowi-eyebrow">ESTRUCTURA DE INVERSIÓN</p><h2 className="mt-4 text-4xl font-semibold">Financiar la obra y también su vida útil.</h2><p className="mt-6 leading-relaxed text-[#bdc4cf]">Cada proyecto necesitará un presupuesto propio, fuentes de financiación verificadas y una proyección de operación. Se estudiarán aportes de promotores, alianzas, filantropía y mecanismos públicos o financieros que resulten adecuados, sin captar fondos desde esta página.</p><p className="mt-5 leading-relaxed text-[#bdc4cf]">Antes de construir debe existir una respuesta documentada a tres preguntas: quién paga la inversión, cómo se sostiene el acceso gratuito y quién asume cada riesgo durante la operación.</p></div><div className="grid gap-4 sm:grid-cols-2">{funds.map((fund,i) => <article key={fund.label} className="cosmos-tile rounded-2xl p-6"><span className="text-sm text-[#e8b37b]">0{i+1} / PARTIDA</span><h3 className="mt-5 text-xl font-semibold">{fund.label}</h3><p className="mt-3 text-sm leading-relaxed text-[#bdc4cf]">{fund.detail}</p></article>)}</div></section>
    <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10" aria-labelledby="decisiones-infraestructura"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">EXPEDIENTE DE CADA PROYECTO</p><h2 id="decisiones-infraestructura" className="mt-4 max-w-4xl text-4xl font-semibold">Evidencia, responsables y aprobación en cada compromiso.</h2><p className="mt-6 max-w-3xl leading-relaxed text-[#bdc4cf]">El estudio debe separar inversión inicial, costes de servicio y una reserva de mejora anual. Las estimaciones incluirían escenarios de demanda y financiación, responsables de cada obligación y un plan si faltan fondos. Ninguna cifra publicada aquí representa una oferta de inversión o un proyecto financiado.</p><div className="mt-9 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[700px] border-collapse text-left text-sm"><thead className="bg-white/5 text-[#e8b37b]"><tr><th scope="col" className="p-5">Decisión</th><th scope="col" className="p-5">Evidencia mínima</th><th scope="col" className="p-5">Quién la valida</th></tr></thead><tbody>{decisionRecord.map((item) => <tr key={item.moment} className="border-t border-white/10 align-top"><th scope="row" className="w-1/5 p-5 font-semibold">{item.moment}</th><td className="w-2/5 p-5 leading-relaxed text-[#bdc4cf]">{item.evidence}</td><td className="w-2/5 p-5 leading-relaxed text-[#bdc4cf]">{item.decision}</td></tr>)}</tbody></table></div><p className="mt-5 text-sm text-[#aeb6c4]">La composición y las competencias del órgano promotor se definirán formalmente antes de tomar decisiones; sus acuerdos no sustituyen licencias, controles profesionales ni la decisión de la Administración.</p></div></section>
    <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><p className="kowi-eyebrow">GOBERNANZA HUMANA</p><h2 className="mt-4 text-4xl font-semibold">Los socios promotores deciden. Los expertos comprueban.</h2><p className="mt-6 leading-relaxed text-[#bdc4cf]">Un grupo definido de socios promotores aprobaría las decisiones de inversión y el paso entre fases, con actas, conflictos de interés declarados y trazabilidad. Consejos de educación, salud, arquitectura, finanzas, comunidad y seguridad aportarían evaluación independiente según el proyecto.</p></div><div className="cosmos-panel rounded-3xl p-8"><h3 className="text-2xl font-semibold">Control que no se delega a la IA</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">KOWI puede organizar estudios, escenarios, tareas y evidencias. Personas habilitadas firman diseños, autorizan pagos, supervisan obras y toman decisiones académicas o clínicas. La comunidad participa en el diagnóstico y la evaluación. La autoridad pública conserva las competencias que le correspondan.</p><p className="mt-5 text-sm text-[#aeb6c4]">Composición, voto y responsabilidades de los consejos todavía deben definirse en la estructura jurídica de cada iniciativa.</p></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:grid-cols-2 md:px-10"><div><p className="kowi-eyebrow">30 AÑOS DESPUÉS DE LA OBRA</p><h2 className="mt-4 text-4xl font-semibold">Administrar, mejorar y preparar la continuidad.</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">Proponemos estudiar una operación de 30 años contados desde la entrega y puesta en servicio de cada obra. Cada año se reservarían recursos para mantenimiento, accesibilidad, actualización y desarrollo; se publicarían indicadores de acceso, calidad, seguridad y estado financiero.</p></div><div className="cosmos-panel rounded-3xl p-8"><h3 className="text-2xl font-semibold">Horizonte de transferencia pública</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">La intención es entregar al gobierno competente una infraestructura cuidada y capaz de seguir sirviendo a las personas al término del período acordado. Titularidad, plazo, operación, personal, financiación, estado de los bienes y aceptación pública deberán pactarse antes de comprometer la inversión. El plazo de 30 años es una propuesta, no un acuerdo vigente ni una regla aplicable a todos los países o proyectos. En España, un convenio público ordinario tiene, por regla general, una duración máxima de cuatro años, prorrogable hasta cuatro más; un horizonte de 30 años exigiría estudiar otro instrumento jurídico específico y obtener el acuerdo previo de la autoridad competente.</p></div></section>
    {infrastructureAgent && <section className="border-t border-white/10 bg-[#0a1120] px-5 py-20 md:px-10" aria-labelledby="agente-infraestructura"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><p className="kowi-eyebrow">AGENTE DEFINIDO EN CATÁLOGO · NO ACTIVO</p><h2 id="agente-infraestructura" className="mt-4 text-4xl font-semibold">Un apoyo para preparar decisiones, nunca para tomarlas solo.</h2><p className="mt-6 leading-relaxed text-[#bdc4cf]">El perfil {infrastructureAgent.name} está definido para ayudar a ordenar diagnósticos, comparar escenarios de inversión, proponer hitos y recopilar evidencias. Es una propuesta de producto; no ejecuta procesos en segundo plano ni está conectado a una obra, cuenta bancaria o entidad pública.</p></div><aside className="cosmos-panel rounded-3xl p-8"><h3 className="text-2xl font-semibold">Límite de autoridad</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">La inversión, contratos, construcción, operación y eventual transferencia pública requieren aprobación humana documentada y los permisos profesionales e institucionales que correspondan. El agente no puede autorizarlos ni enviarlos por sí mismo.</p><Link href="/pro" className="mt-6 inline-flex text-sm font-semibold text-[#e8b37b]">Ver el catálogo de agentes ↗</Link></aside></div></section>}
    <section className="border-t border-white/10 px-5 py-14 md:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><p className="max-w-2xl text-lg text-[#c5cad3]">El primer paso no es construir un edificio: es encontrar una necesidad real y a las personas capaces de diseñar una respuesta sostenible.</p><Link href="/fundacion/modelo" className="kowi-gold-btn rounded-full px-6 py-3 font-semibold">Ver gobernanza y financiación ↗</Link></div></section>
    <footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 border-t border-white/10 px-5 py-8 text-sm text-[#aeb6c4] md:px-10"><Link href="/fundacion">← Iniciativa de impacto KOWI</Link><Link href="/privacidad">Privacidad</Link></footer>
  </main>;
}
