'use client';
import { useState } from 'react';
import Link from 'next/link';

const cases = [
  { sector:'Peluquería', name:'Studio Raíz', intro:'Hola, soy el asistente de Studio Raíz. ¿Qué servicio te interesa y qué día te vendría bien?', prompt:'Quiero pedir una cita para corte y color el viernes por la tarde.', response:'¡Gracias! Para preparar tu solicitud de corte y color del viernes por la tarde, ¿me indicas tu nombre y una forma de contacto? El equipo confirmará horario y precio antes de reservar.', action:'Solicitud de cita preparada', fields:['Servicio: corte y color','Preferencia: viernes por la tarde','Pendiente: nombre y contacto','Revisión humana: confirmación y precio'] },
  { sector:'Clínica dental', name:'Clínica Sonrisa', intro:'Hola, te ayudo a preparar una consulta para el equipo de Clínica Sonrisa. ¿Qué necesitas?', prompt:'Quiero información sobre una limpieza dental y una cita.', response:'Puedo preparar tu solicitud. ¿Cuál es tu nombre y qué horario prefieres? El equipo de la clínica te confirmará disponibilidad, precio y cualquier indicación clínica.', action:'Consulta para recepción', fields:['Interés: limpieza dental','Pendiente: nombre y horario','Revisión humana: disponibilidad e indicaciones','Sin diagnóstico automatizado'] },
  { sector:'Inmobiliaria', name:'Vivienda Norte', intro:'Hola, te ayudo a encontrar opciones. ¿Buscas comprar o alquilar y en qué zona?', prompt:'Busco comprar un piso de dos habitaciones cerca de Madrid.', response:'Entendido: compra de piso de dos habitaciones cerca de Madrid. ¿Qué presupuesto aproximado y qué municipios te interesan? Con esos datos el equipo podrá proponerte opciones y concertar visitas.', action:'Oportunidad comercial preparada', fields:['Operación: compra','Tipo: piso de 2 habitaciones','Zona: entorno de Madrid','Pendiente: presupuesto y municipios'] },
];
export default function Demo() {
  const [selected,setSelected]=useState(0);
  const [message,setMessage]=useState('');
  const [sent,setSent]=useState(false);
  const current=cases[selected];
  function select(index:number){setSelected(index);setMessage('');setSent(false);}
  return <main className="min-h-screen bg-[#edf2e8] text-[#193d32]">
    <header className="border-b border-[#d4dfcd] bg-[#10372f] px-6 py-5 text-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><Link href="/" className="font-bold tracking-[.17em]">KOWI ONE</Link><a href="mailto:info@kowi.one?subject=Solicitar%20piloto%20Kowi%20Business" className="rounded-full bg-[#d9efae] px-5 py-2 text-sm font-semibold text-[#193d32]">Solicitar piloto ↗</a></div></header>
    <div className="mx-auto max-w-6xl px-6 py-12"><p className="eyebrow text-[#66865d]">KOWI BUSINESS · DEMOSTRACIÓN</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight md:text-5xl">Mira cómo empieza una conversación con tu cliente.</h1><p className="mt-5 max-w-3xl text-lg text-[#53695c]">Elige un sector y prueba un caso. Esta demo muestra un flujo de ejemplo; aún no envía mensajes, reserva citas ni se conecta a WhatsApp, correo o CRM.</p>
      <div className="mt-8 flex flex-wrap gap-3" role="group" aria-label="Elegir sector">{cases.map((item,index)=><button type="button" key={item.sector} onClick={()=>select(index)} aria-pressed={selected===index} className={`rounded-full px-5 py-3 font-medium ${selected===index?'bg-[#194538] text-white':'border border-[#b9cfb8] bg-white'}`}>{item.sector}</button>)}</div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="overflow-hidden rounded-[1.5rem] border border-[#d4dfcd] bg-white shadow-sm" aria-label="Conversación de ejemplo"><div className="border-b border-[#e2e9dc] p-5"><h2 className="text-xl font-semibold">{current.name}</h2><p className="text-sm text-[#65776a]">Ejemplo de atención al cliente</p></div><div className="flex min-h-[320px] flex-col gap-4 p-5" aria-live="polite"><p className="max-w-[85%] self-start rounded-2xl rounded-tl-sm bg-[#eef3e8] p-4 leading-relaxed">{current.intro}</p>{sent && <><p className="max-w-[85%] self-end rounded-2xl rounded-tr-sm bg-[#dcecab] p-4 leading-relaxed">{message}</p><p className="max-w-[85%] self-start rounded-2xl rounded-tl-sm bg-[#eef3e8] p-4 leading-relaxed">{current.response}</p></>}</div><div className="border-t border-[#e2e9dc] p-5"><button type="button" onClick={()=>{setMessage(current.prompt);setSent(true);}} className="w-full rounded-xl bg-[#194538] p-4 font-semibold text-white hover:bg-[#28634d]">{sent?'Repetir ejemplo':'Enviar consulta de ejemplo'} ↗</button></div></section>
      <aside className="rounded-[1.5rem] bg-[#dcebab] p-7"><p className="eyebrow">LO QUE PREPARA KOWI</p><h2 className="mt-5 text-2xl font-semibold">{sent?current.action:'Una conversación útil para tu equipo'}</h2><ul className="mt-6 space-y-3">{(sent?current.fields:['Escucha la necesidad del cliente','Pide solo los datos necesarios','Organiza el siguiente paso','Deja las acciones sensibles al equipo']).map(text=><li key={text} className="border-b border-[#849b6c]/30 pb-3">{text}</li>)}</ul><p className="mt-8 text-sm leading-relaxed">Para activar canales reales, agenda o CRM se requiere configurar cada integración y acordar permisos con el negocio.</p><a href="mailto:info@kowi.one?subject=Quiero%20un%20piloto%20de%20Kowi%20Business" className="mt-6 inline-block rounded-full bg-[#194538] px-6 py-3 font-semibold text-white">Hablemos de tu piloto ↗</a></aside></div>
    </div>
  </main>;
}
