import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Modelo de impacto y gobernanza | KOWI',
  description: 'Propuesta de educación gratuita, gobernanza humana, financiación verificable e infraestructura futura para la iniciativa de impacto KOWI.',
};

const steps = [
  { title: '1. Aprender gratis', work: 'Publicar materiales abiertos en KOWI School y ofrecer una primera experiencia educativa gratuita de alcance limitado, con docentes y accesibilidad.', evidence: 'Personas participantes, finalización voluntaria, aprendizaje antes/después, accesibilidad y coste real por participante.' },
  { title: '2. Escuchar y corregir', work: 'Recoger evaluación anónima y entrevistas consentidas; contrastar las necesidades con una mesa comunitaria y profesionales.', evidence: 'Acta de propuestas, objeciones respondidas, cambios aplicados y resultados comparables con la línea de base.' },
  { title: '3. Probar presencia física', work: 'Si la evaluación justifica avanzar, estudiar espacios compartidos y un piloto presencial con entidad habilitada, antes de proyectar obra propia.', evidence: 'Demanda local, seguridad, equipo profesional, coste de uso y autorización o acuerdo del titular del espacio.' },
  { title: '4. Estudiar infraestructura', work: 'Solo después, analizar por separado escuela, centro de salud, universidad u hospital con la autoridad competente y especialistas.', evidence: 'Viabilidad técnica, jurídica y económica; capacidad de operación; presupuesto de obra y servicio; decisión humana documentada.' },
];

const finance = [
  { bucket: 'Preparación', requirement: 'Diagnóstico, diseño pedagógico o sanitario, asesoramiento, permisos y estudios de suelo. Fuente identificada antes de gastar.' },
  { bucket: 'Capital', requirement: 'Obra, equipamiento, contingencia y pruebas. No iniciar construcción por una promesa de ingresos futuros.' },
  { bucket: 'Servicio anual', requirement: 'Personal, suministros, materiales, seguros, mantenimiento y costes administrativos. Cobertura plurianual documentada.' },
  { bucket: 'Reserva y continuidad', requirement: 'Fondo de renovación y emergencias, obligaciones pendientes y continuidad del servicio para la comunidad.' },
];

const sources = [
  { label: 'Ley 50/2002, arts. 3, 4, 12, 14, 15 y 23–28', href: 'https://www.boe.es/buscar/act.php?id=BOE-A-2002-25180' },
  { label: 'Registro de Fundaciones de la Comunidad de Madrid', href: 'https://sede.comunidad.madrid/inscripciones-registro/registro-fundaciones' },
  { label: 'Ley 38/2003, subvenciones, art. 13', href: 'https://www.boe.es/buscar/act.php?id=BOE-A-2003-20977' },
  { label: 'Base de Datos Nacional de Subvenciones', href: 'https://www.pap.hacienda.gob.es/bdnstrans/GE/es/convocatorias' },
];

export default function FoundationModel() {
  return <main className="kowi-cosmos min-h-screen">
    <header className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-7 md:px-10"><Link href="/fundacion" className="inline-flex items-center gap-3 text-[#e8b37b]"><span className="kowi-emblem" aria-hidden="true"/><span className="font-semibold tracking-[.28em]">KOWI</span></Link><Link href="/fundacion" className="text-sm text-[#c6c9d0]">← Volver a la iniciativa</Link></header>
    <section className="border-y border-white/10 bg-[radial-gradient(circle_at_75%_25%,#b57b4b25,transparent_38%),linear-gradient(130deg,#142339,#060b16_65%)] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">INICIATIVA DE IMPACTO · MODELO PROPUESTO</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.08] tracking-tight md:text-7xl">Primero demostrar el cuidado. <span className="text-[#e8b37b]">Después construir.</span></h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-[#c5cad3]">KOWI quiere empezar con educación gratuita evaluable y avanzar, si la evidencia lo respalda, hacia espacios físicos de aprendizaje y salud. Esta página propone cómo decidir, financiar y rendir cuentas; no anuncia una fundación constituida, una convocatoria, financiación disponible ni un acuerdo público.</p><a href="#piloto" className="mt-8 inline-flex rounded-full border border-white/30 px-6 py-3">Ver el primer piloto ↓</a></div></section>
    <section id="piloto" className="mx-auto max-w-7xl px-5 py-20 md:px-10"><p className="kowi-eyebrow">PILOTO DE BAJO COSTE</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold">La educación gratuita es la primera prueba de impacto.</h2><div className="mt-9 grid gap-4 md:grid-cols-2">{steps.map(step=><article key={step.title} className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">{step.title}</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">{step.work}</p><p className="mt-5 border-t border-white/10 pt-4 text-sm text-[#e5cfb9]">Evidencia: {step.evidence}</p></article>)}</div><p className="mt-7 max-w-3xl text-sm text-[#aeb6c4]">Criterio de avance propuesto: comparar resultados con la situación inicial, escuchar a participantes y profesionales, comprobar capacidad financiera y resolver objeciones de seguridad y acceso. Si los resultados no sostienen el siguiente paso, se rediseña el piloto.</p><Link href="/school" className="kowi-gold-btn mt-7 inline-flex rounded-full px-7 py-3 font-semibold">Explorar guías gratuitas ↗</Link></section>
    <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">GOBERNANZA A SOMETER A REVISIÓN</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold">Decisión institucional, revisión profesional y voz comunitaria.</h2><div className="mt-9 grid gap-4 lg:grid-cols-3"><article className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">Órgano responsable</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">Si se constituye una fundación, tendría un Patronato de al menos tres personas. Modelo a estudiar: cinco puestos, con representación fundadora, dos profesionales independientes y dos voces comunitarias. Para inversión mayor, propuesta de cuatro votos favorables sobre cinco, incluida una voz independiente y una comunitaria, siempre sujeta a estatutos y asesoría.</p></article><article className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">Consenso antes de crecer</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">Dos rondas de escucha con personas usuarias y profesionales; acta pública de alternativas, apoyos y objeciones. Una objeción fundada de seguridad, accesibilidad o exclusión obliga a revisar el diseño antes de votar. El consejo comunitario orienta; no sustituye las atribuciones del Patronato ni de autoridades.</p></article><article className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">Integridad</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">Declaración de intereses, abstención de quien tenga conflicto, actas y revisión externa proporcionada al riesgo. Ningún proyecto tendrá como finalidad principal beneficiar al fundador, patronos o allegados. Cualquier contratación con patronos exigiría las autorizaciones que correspondan.</p></article></div><p className="mt-7 max-w-4xl text-sm text-[#aeb6c4]">Esta composición y mayoría son una propuesta, no estatutos aprobados. La ley exige que el Patronato adopte acuerdos según los estatutos y administre el patrimonio con diligencia; la consulta comunitaria no crea representación legal por sí sola.</p></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:px-10"><p className="kowi-eyebrow">FINANCIACIÓN VERIFICABLE</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold">Presupuestar la apertura y todos los años de servicio.</h2><p className="mt-6 max-w-4xl leading-relaxed text-[#bdc4cf]">Para cada proyecto: inversión inicial = preparación + suelo o uso + obra + equipos + contingencia. Para cada año: financiación confirmada debe cubrir personal + operación + mantenimiento + reserva de mejora. Se calcularán escenarios de demanda y costes; si falta cobertura de continuidad, el proyecto no pasa a obra.</p><div className="mt-9 grid gap-4 sm:grid-cols-2">{finance.map(item=><article key={item.bucket} className="cosmos-tile rounded-2xl p-6"><h3 className="text-xl font-semibold">{item.bucket}</h3><p className="mt-3 text-sm leading-relaxed text-[#bdc4cf]">{item.requirement}</p></article>)}</div><p className="mt-7 max-w-4xl leading-relaxed text-[#bdc4cf]">Fuentes posibles a estudiar: aportaciones propias legalmente comprometidas, colaboración filantrópica bajo estructura habilitada y ayudas públicas que cumplan las bases de una convocatoria concreta. La BDNS sirve para buscar convocatorias, no garantiza elegibilidad ni concesión. KOWI Business y esta futura entidad mantendrían órganos, patrimonio y cuentas separados. Un eventual apoyo de Business requeriría acuerdo escrito, valoración de conflictos y registro contable; hoy no se afirma que sus ingresos financien esta iniciativa.</p></section>
    <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2"><div><p className="kowi-eyebrow">RUTA LEGAL EN MADRID</p><h2 className="mt-4 text-4xl font-semibold">Constituir antes de actuar en nombre de una fundación.</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">Primero habría que definir fines, ámbito territorial, estatutos, Patronato y dotación adecuada; la ley presume suficiente una dotación de 30.000 €. La denominación de «Fundación» corresponde a entidades inscritas. Si la actividad principal fuese en Madrid, la sede autonómica indica escritura pública, certificados de dotación, reserva de nombre, plan de actuación, estudio de viabilidad e inscripción. Se necesita revisión jurídica de competencia y documentación antes de presentar nada.</p></div><div><p className="kowi-eyebrow">COLABORACIÓN PÚBLICA</p><h2 className="mt-4 text-4xl font-semibold">Solicitar apoyo para proyectos concretos.</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">La iniciativa puede estudiar ayudas, cesión de uso de espacios o alianzas institucionales cuando una convocatoria o propuesta concreta lo permita. Cada opción exige verificar requisitos, responsabilidades y financiación. La misión se sostiene en el beneficio público y la continuidad de cada servicio.</p></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:px-10"><p className="kowi-eyebrow">AGENTE DE FORMACIÓN · PERFIL PROPUESTO</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold">Seguimiento útil, decisiones humanas.</h2><div className="mt-8 grid gap-4 md:grid-cols-2"><article className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">Trabajo que se puede automatizar</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">Vigilar novedades en BOE, Comunidad de Madrid y BDNS; mantener una lista de requisitos con fecha y fuente; preparar borradores de expediente; resumir objeciones comunitarias e indicadores. Cada alerta debe enlazar al documento oficial y distinguir un cambio de norma de una convocatoria específica.</p></article><article className="cosmos-panel rounded-3xl p-7"><h3 className="text-2xl font-semibold">Puertas que no cruza el agente</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">Fabián y profesionales habilitados revisan las conclusiones. Presentar escrituras o solicitudes, contactar a terceros, pedir dinero, asumir compromisos, modificar permisos o comunicar acuerdos requiere autorización humana expresa y, cuando corresponda, la entidad ya constituida.</p></article></div><p className="mt-5 text-sm text-[#aeb6c4]">Foundation Formation Agent está definido en el catálogo de KOWI como perfil propuesto. Esta página no inicia un proceso autónomo de vigilancia ni equivale a seguimiento legal activo.</p><Link href="/pro" className="mt-6 inline-flex text-sm font-semibold text-[#e8b37b]">Ver perfil en catálogo ↗</Link></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:px-10"><p className="kowi-eyebrow">FUENTES PRIMARIAS</p><h2 className="mt-4 text-3xl font-semibold">Normas y trámites para verificar cada paso.</h2><ul className="mt-6 space-y-3 text-[#c5cad3]">{sources.map(source=><li key={source.href}><a href={source.href} target="_blank" rel="noreferrer" className="underline decoration-[#e8b37b]/60 underline-offset-4">{source.label} ↗</a></li>)}</ul><p className="mt-5 max-w-3xl text-sm text-[#aeb6c4]">Este modelo es una propuesta de producto e impacto, no asesoramiento jurídico ni una solicitud administrativa.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/fundacion/infraestructura" className="kowi-gold-btn rounded-full px-6 py-3 font-semibold">Ver fases de infraestructura ↗</Link><Link href="/fundacion" className="rounded-full border border-white/30 px-6 py-3">Volver a la iniciativa</Link></div></section>
  </main>;
}
