'use client';
import {useState} from 'react';
import type {SchoolLevel} from '@/lib/school/curriculum';
const stages=[['DESCUBRE','discover'],['APRENDE','learn'],['PRUEBA','tryIt'],['CONSTRUYE','build'],['ROMPE','breakIt'],['CORRIGE','fix'],['EJECUTA','execute'],['EXPLICA','explain'],['DEMUESTRA','prove'],['EVIDENCIA','evidence'],['SIGUIENTE RETO','next']] as const;
export default function UnitClient({level}:{level:SchoolLevel}){
 const [done,setDone]=useState<number[]>([]);const [evidence,setEvidence]=useState('');const [notice,setNotice]=useState('');
 function toggle(i:number){setDone(d=>d.includes(i)?d.filter(x=>x!==i):[...d,i]);}
 function save(){if(evidence.trim().length<20){setNotice('Describe la evidencia con suficiente detalle antes de guardarla.');return;}const item={level:level.id,title:level.title,evidence:evidence.trim(),created_at:new Date().toISOString(),verified:false};try{const old=JSON.parse(localStorage.getItem('kowi-school-evidence')||'[]');localStorage.setItem('kowi-school-evidence',JSON.stringify([...old,item]));setNotice('Evidencia guardada en este dispositivo. Estado: pendiente de verificación.');}catch{setNotice('No se pudo guardar en este navegador.');}}
 return <div className="mt-8 space-y-3">{stages.map(([label,key],i)=><section key={key} className="rounded-2xl border border-[#e0e3df] bg-white p-5"><div className="flex gap-4"><button aria-label={'Marcar '+label} aria-pressed={done.includes(i)} onClick={()=>toggle(i)} className="mt-1 h-6 w-6 shrink-0 rounded-full border border-[#6c8777] text-xs">{done.includes(i)?'✓':''}</button><div><p className="font-mono text-xs font-semibold tracking-[.15em] text-[#4f765f]">{label}</p><p className="mt-2 leading-7">{level.unit[key]}</p>{label==='EVIDENCIA'&&<><textarea value={evidence} onChange={e=>setEvidence(e.target.value)} className="mt-4 w-full rounded-xl border border-[#d8ddd9] p-3" rows={4} placeholder="Qué hiciste, cómo lo probaste, resultado y enlace permitido si existe…"/><button onClick={save} className="mt-3 rounded-full bg-[#173e2d] px-5 py-2 text-sm font-semibold text-white">Guardar evidencia</button>{notice&&<p role="status" className="mt-2 text-sm text-[#56635c]">{notice}</p>}</>}</div></div></section>)}</div>
}