import Link from 'next/link';
import { kowiAgents } from '@/lib/agents/registry';

export default function KowiPro(){
 const agents=kowiAgents.filter(a=>a.access==='pro');
 return <main className="kowi-cosmos min-h-screen px-6 py-12 text-[#f4f3f2]"><div className="mx-auto max-w-7xl">
  <Link href="/" className="text-[#e8b37b]">← KOWI</Link>
  <p className="mt-12 text-xs font-semibold uppercase tracking-[.25em] text-[#e8b37b]">KOWI PRO · AGENT OS</p>
  <h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-tight">Un orquestador. Agentes especializados. Control humano verificable.</h1>
  <p className="mt-6 max-w-3xl text-lg text-[#b9bfca]">KOWI comprende el objetivo y deriva el trabajo al agente adecuado. Cada agente tiene una identidad, capacidades limitadas y acciones que requieren aprobación. Ningún agente obtiene permisos por lo que diga una conversación.</p>
  <div className="mt-10 cosmos-panel rounded-[2rem] p-7"><div className="flex flex-wrap items-center gap-4"><span className="kowi-emblem"/><div><h2 className="text-2xl font-semibold">KOWI Orchestrator</h2><p className="text-[#b9bfca]">Intención → agente → política de riesgo → aprobación → ejecución → evidencia → Action Ledger</p></div></div></div>
  <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{agents.map(a=><article key={a.id} className="cosmos-tile rounded-2xl p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">{a.name}</h2><span className="rounded-full border border-[#e8b37b]/30 px-3 py-1 text-xs text-[#e8b37b]">{a.availability==='proposed'?'Propuesto':`${a.risk} risk`}</span></div><p className="mt-3 text-sm leading-relaxed text-[#b9bfca]">{a.role}</p><p className="mt-5 text-xs uppercase tracking-wider text-[#e8b37b]">Capacidades</p><p className="mt-2 text-sm">{a.capabilities.join(' · ')}</p><p className="mt-5 text-xs uppercase tracking-wider text-[#e8b37b]">Human approval</p><p className="mt-2 text-sm text-[#b9bfca]">{a.requiresApproval.length?a.requiresApproval.join(' · '):'No requerido para funciones informativas'}</p>{a.availability==='proposed'&&<p className="mt-5 border-t border-white/10 pt-4 text-xs text-[#b9bfca]">Perfil de planificación. No está conectado a procesos ni ejecuta acciones en segundo plano.</p>}</article>)}</section>
  <section className="mt-10 rounded-2xl border border-white/10 p-6"><h2 className="text-2xl font-semibold">Seguridad por diseño</h2><p className="mt-3 text-[#b9bfca]">Deny-by-default · mínimo privilegio · separación lectura/escritura · aprobación humana en alto impacto · ledger append-only · canales externos solo tras verificación. Los conectores aún no verificados permanecen bloqueados.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/pro/intelligence" className="kowi-gold-btn rounded-full px-6 py-3 font-semibold">Abrir Intelligence Center ↗</Link><Link href="/business" className="rounded-full border border-white/20 px-6 py-3">Abrir KOWI Business ↗</Link><Link href="/business/agent" className="rounded-full border border-white/20 px-6 py-3">CRM y aprobaciones</Link></div></section>
 </div></main>
}
