import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Comunidad | KOWI', description: 'La visión de una comunidad que conecta ideas, conocimiento y colaboración. Empieza hoy con Kowi One y Proyectos.' };

export default function Comunidad() { return <main className="kowi-cosmos min-h-screen">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-7 md:px-10"><Link href="/" className="inline-flex items-center gap-3 text-[#e8b37b]"><span className="kowi-emblem" aria-hidden="true"/><span className="font-semibold tracking-[.28em]">KOWI</span></Link><Link href="/organizacion" className="text-sm text-[#c6c9d0]">El ecosistema ↗</Link></header>
  <section className="border-y border-white/10 bg-[radial-gradient(circle_at_78%_26%,#7d99ac21,transparent_36%),linear-gradient(130deg,#152338,#060b16_65%)] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">KOWI COMUNIDAD · EN DESARROLLO</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.08] tracking-tight md:text-7xl">Las ideas avanzan cuando <span className="text-[#e8b37b]">encontramos a otros.</span></h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-[#c5cad3]">Queremos crear un espacio donde personas con proyectos, profesionales y negocios puedan compartir conocimiento y encontrar formas responsables de colaborar. Hoy puedes empezar tu camino individual; la red de miembros aún está en construcción.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/kowi" className="kowi-gold-btn rounded-full px-7 py-3 font-semibold">Empezar una idea ↗</Link><a href="#camino" className="rounded-full border border-white/25 px-7 py-3">Cómo participar ↓</a></div></div></section>
  <section id="camino" className="mx-auto max-w-7xl px-5 py-20 md:px-10"><p className="kowi-eyebrow">TU PUNTO DE PARTIDA</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight md:text-5xl">Hay una forma de empezar ahora.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{[
    { n:'01',title:'Cuenta tu intención',description:'Habla con Kowi sobre lo que quieres crear, cambiar o resolver. Dale forma a un objetivo y una primera acción.',href:'/kowi',cta:'Ir a Kowi One' },
    { n:'02',title:'Organiza el proyecto',description:'Divide la idea en fases y tareas. Conserva el contexto de tu propio trabajo en un espacio privado.',href:'/proyectos',cta:'Ir a Proyectos' },
    { n:'03',title:'Comparte una propuesta',description:'Si tienes experiencia o una iniciativa que podría conectar con Kowi, abre una conversación con el equipo.',href:'mailto:info@kowi.one?subject=Colaborar%20con%20la%20Comunidad%20KOWI',cta:'Escribir a Kowi' },
  ].map(item => <article key={item.n} className="cosmos-panel flex flex-col rounded-3xl p-7"><span className="text-sm text-[#e8b37b]">{item.n} / EMPEZAR</span><h3 className="mt-8 text-2xl font-semibold">{item.title}</h3><p className="mt-4 flex-1 leading-relaxed text-[#bdc4cf]">{item.description}</p><Link href={item.href} className="mt-8 font-semibold text-[#e8b37b]">{item.cta} ↗</Link></article>)}</div></section>
  <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="kowi-eyebrow">LA RED QUE IMAGINAMOS</p><h2 className="mt-4 text-4xl font-semibold">Colaboración con propósito y confianza.</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">La comunidad futura debe ayudar a que cada conexión tenga un motivo claro y respete el trabajo de quienes participan.</p></div><div className="grid gap-4 sm:grid-cols-2">{[['Ideas','Un espacio para explicar necesidades y objetivos.'],['Capacidades','Personas que aportan conocimiento y experiencia.'],['Proyectos','Pasos definidos, responsabilidades y avances visibles.'],['Cuidado','Consentimiento, privacidad y decisión humana al compartir.']].map(([title,description]) => <div key={title} className="cosmos-tile rounded-2xl p-6"><h3 className="text-xl font-semibold text-[#f1caa2]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#bdc4cf]">{description}</p></div>)}</div></div></section>
  <section className="mx-auto flex max-w-7xl flex-wrap items-end justify-between gap-8 px-5 py-20 md:px-10"><div className="max-w-3xl"><p className="kowi-eyebrow">ESTADO DE LA COMUNIDAD</p><h2 className="mt-4 text-3xl font-semibold">La participación comienza con una conversación.</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">Los perfiles públicos, las conexiones entre miembros, los proyectos compartidos y las convocatorias todavía no están disponibles. El contacto por correo sirve para propuestas; no crea una cuenta de miembro ni garantiza una respuesta o incorporación.</p></div><Link href="/organizacion" className="rounded-full border border-[#e8b37b]/50 px-6 py-3 text-[#e8b37b]">Conocer Kowi ↗</Link></section>
  <footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 border-t border-white/10 px-5 py-8 text-sm text-[#aeb6c4] md:px-10"><Link href="/">← Volver al inicio</Link><div className="flex gap-5"><Link href="/fundacion">Fundación</Link><Link href="/privacidad">Privacidad</Link></div></footer>
</main>; }
