import type {Metadata} from 'next';
import Link from 'next/link';
import {newsBriefings,newsSources} from '@/lib/news';
import {loadNewsRadar} from '@/lib/server/news';
export const revalidate=3600;
export const metadata:Metadata={title:'KOWI News · Tecnología con propósito humano',description:'Noticias tecnológicas con fuentes oficiales, fechas, interpretación y próximos pasos para aprender a utilizar IA con criterio.'};
const date=(value:string)=>new Intl.DateTimeFormat('es',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(value));
export default async function News(){
 const radar=await loadNewsRadar();
 return <main className="kowi-cosmos min-h-screen px-5 py-9 text-[#f4f3f2] md:px-10"><div className="mx-auto max-w-6xl space-y-10">
 <header className="flex flex-wrap items-center justify-between gap-4"><Link href="/" className="text-xl font-semibold tracking-widest text-[#e8b37b]">KOWI</Link><Link href="/app" className="rounded-full border border-white/30 px-5 py-3">Mi espacio KOWI</Link></header>
 <section><p className="kowi-eyebrow">NEWS · ACTUALIDAD HUMAN-FIRST</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-tight md:text-6xl">El futuro se comprende. Después se construye.</h1><p className="mt-6 max-w-3xl text-lg text-[#bdc4cf]">Qué está cambiando en la tecnología, por qué puede importarte y cómo convertir una novedad en aprendizaje y acciones bajo control humano.</p><nav aria-label="Secciones de News" className="mt-6 flex flex-wrap gap-5 underline"><a href="#radar">Últimos 90 días</a><a href="#lecturas">Lecturas con contexto</a><a href="#decisiones">Decidir sobre IA</a><a href="#comunicaciones">Comunicación y comunidad</a></nav></section>
 <section id="radar"><p className="kowi-eyebrow">FUENTES PRIMARIAS · LANZAMIENTOS OFICIALES</p><h2 className="mt-3 text-3xl">Radar tecnológico</h2><p className="mt-4 text-[#bdc4cf]">Selección de versiones estables publicadas en los últimos 90 días. Consulta las notas oficiales para conocer su alcance; un lanzamiento no garantiza acceso a todas sus funciones.</p><p className="mt-3 text-sm text-[#aeb6c4]">Página generada: {date(radar.checkedAt)}. Consulta de fuentes almacenada hasta una hora; esta selección no cubre toda la actualidad tecnológica.</p>
 {!!radar.unavailable.length&&<p role="status" className="mt-4 rounded-xl border border-[#e8b37b]/40 p-4">No se pudo consultar: {radar.unavailable.join(', ')}. Puedes abrir las fuentes oficiales; no se han inventado titulares para cubrir esa ausencia.</p>}
 {!radar.releases.length&&<p className="mt-5">No hay lanzamientos recientes verificables disponibles en esta consulta.</p>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{radar.releases.map(r=><article key={r.url} className="cosmos-panel rounded-2xl p-6"><p className="text-sm text-[#e8b37b]">{r.source}</p><h3 className="mt-4 break-words text-xl">{r.title}</h3><p className="mt-3 text-sm text-[#aeb6c4]">Publicado: <time dateTime={r.publishedAt}>{date(r.publishedAt)}</time></p><p className="mt-4 text-[#bdc4cf]">{r.topic}</p><a href={r.url} target="_blank" rel="noopener noreferrer" className="mt-5 inline-block text-[#e8b37b] underline">Leer anuncio oficial ↗</a></article>)}</div>
 <details className="mt-6"><summary className="cursor-pointer">Fuentes que seguimos</summary><ul className="mt-3 space-y-3">{newsSources.map(s=><li key={s.repo}><a className="underline" href={'https://github.com/'+s.repo+'/releases'} target="_blank" rel="noopener noreferrer">{s.label} ↗</a></li>)}</ul></details></section>
 <section id="lecturas"><p className="kowi-eyebrow">OBSERVAR · COMPRENDER · DECIDIR</p><h2 className="mt-3 text-3xl">Lo que estas novedades pueden significar</h2><div className="mt-6 space-y-5">{newsBriefings.map(b=><article key={b.id} className="cosmos-panel rounded-2xl p-6 md:p-8"><p className="text-sm text-[#aeb6c4]">Fuente publicada: {date(b.publishedAt)} · Lectura editorial KOWI: 4 oct 2026</p><h3 className="mt-4 text-2xl">{b.title}</h3><div className="mt-6 grid gap-5 md:grid-cols-3">{[['Dato observado',b.observed],['Interpretación KOWI',b.interpretation],['Siguiente paso recomendado',b.recommendation]].map(([label,text])=><div key={label}><h4 className="font-semibold text-[#e8b37b]">{label}</h4><p className="mt-3 leading-relaxed text-[#bdc4cf]">{text}</p></div>)}</div><a className="mt-6 inline-block underline" href={b.url} target="_blank" rel="noopener noreferrer">Comprobar fuente: {b.source} ↗</a></article>)}</div></section>
 <section id="decisiones" className="cosmos-panel rounded-2xl p-6 md:p-8"><p className="kowi-eyebrow">CAPACIDAD HUMANA · APRENDIZAJE CONTINUO</p><h2 className="mt-4 text-3xl">¿Qué podemos perder si dejamos de aprender sobre IA?</h2><p className="mt-5 max-w-4xl leading-relaxed text-[#bdc4cf]">Ignorar estas herramientas puede retrasar mejoras en tareas repetitivas, dificultar comprender decisiones tecnológicas y aumentar la dependencia de quienes sí las conocen. Son riesgos posibles: su impacto depende del trabajo, los recursos y el contexto de cada persona u organización.</p><p className="mt-4 max-w-4xl leading-relaxed text-[#bdc4cf]">Adoptar IA también exige evaluar coste, errores, privacidad y utilidad. Una buena decisión empieza con un problema concreto, una prueba pequeña y una comparación con el método actual. Conserva lo que funciona y mejora solo cuando la evidencia lo justifique.</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Aprende','Comprende posibilidades, límites y cómo verificar respuestas.'],['Prueba','Elige una tarea, mide tiempo y calidad y escucha a quienes la realizan.'],['Decide','Revisa el resultado y autoriza el siguiente paso con un responsable humano.']].map(([title,body])=><div key={title} className="rounded-xl border border-white/15 p-4"><h3 className="text-xl">{title}</h3><p className="mt-3 text-[#bdc4cf]">{body}</p></div>)}</div><Link href="/school" className="kowi-gold-btn mt-7 inline-block rounded-full px-6 py-3 font-semibold">Aprender con KOWI School ↗</Link></section>
 <section id="comunicaciones" className="cosmos-panel rounded-2xl p-6 md:p-8"><p className="kowi-eyebrow">MARCA · ACTUALIDAD · COMUNIDAD</p><h2 className="mt-4 text-3xl">KOWI Communications</h2><p className="mt-5 text-[#bdc4cf]">Especialidad para organizar la voz de KOWI: contrastar fuentes, preparar contenido útil, cuidar la identidad Human-First y proponer mensajes que inviten a participar. El director puede crear ese trabajo interno con aval del propietario; publicar contenido editorial o enviar campañas requiere su revisión y autorización específica.</p><div className="mt-6 flex flex-wrap gap-4"><Link href="/business/director?kind=communications" className="kowi-gold-btn rounded-full px-6 py-3 font-semibold">Preparar una orden de comunicación ↗</Link><Link href="/fundacion" className="rounded-full border border-white/30 px-6 py-3">Conocer la iniciativa Fundación</Link></div><p className="mt-5 text-sm text-[#aeb6c4]">El radar consulta metadatos públicos de fuentes predefinidas. No hay un agente de IA publicando artículos o enviando mensajes autónomamente.</p></section>
 <footer className="flex flex-wrap gap-5 border-t border-white/15 py-6 text-sm"><Link href="/privacidad">Privacidad y uso de IA</Link><Link href="/business">KOWI Business</Link><Link href="/pro">Agentes especializados</Link></footer>
 </div></main>;
}
