import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Organización | KOWI', description: 'Conoce cómo se conectan Kowi One, Business, Proyectos, School, Comunidad y la iniciativa Fundación KOWI.' };

const areas = [
  { name:'Kowi One', state:'Piloto', text:'Un espacio personal para convertir una intención en un objetivo, un plan y una primera acción.', href:'/kowi' },
  { name:'Kowi Business', state:'Piloto', text:'Agente de empresa, conversación y seguimiento comercial con aprobación humana.', href:'/business' },
  { name:'Kowi Proyectos', state:'Piloto', text:'Ideas organizadas en fases, tareas y próximos pasos.', href:'/proyectos' },
  { name:'Kowi School', state:'En desarrollo', text:'Aprendizaje aplicado a problemas reales y proyectos propios.', href:'/school' },
  { name:'Kowi Comunidad', state:'En desarrollo', text:'Una futura red de personas, conocimientos y capacidades.', href:'/comunidad' },
  { name:'Fundación KOWI', state:'Iniciativa en desarrollo', text:'Una visión de impacto para ampliar oportunidades. Aún no es una fundación constituida.', href:'/fundacion' },
];
export default function Organization() { return <main className="kowi-cosmos min-h-screen">
  <header className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-7 md:px-10"><Link href="/" className="inline-flex items-center gap-3 text-[#e8b37b]"><span className="kowi-emblem" aria-hidden="true"/><span className="font-semibold tracking-[.28em]">KOWI</span></Link><nav aria-label="Secciones de Kowi" className="flex flex-wrap justify-end gap-4 text-sm text-[#bdc4cf]"><Link href="/business">Business</Link><Link href="/proyectos">Proyectos</Link><Link href="/comunidad">Comunidad</Link></nav></header>
  <section className="border-y border-white/10 bg-[radial-gradient(circle_at_76%_28%,#9e63401f,transparent_35%),linear-gradient(125deg,#111d31,#050913_65%)] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">LA ORGANIZACIÓN KOWI</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.08] tracking-tight md:text-7xl">Una inteligencia para empezar.<br/><span className="text-[#e8b37b]">Un ecosistema para avanzar.</span></h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-[#c4cad3]">Una buena intención necesita escucha, conocimiento, un plan y personas capaces de llevarla a la práctica. Kowi conecta productos digitales con una visión de aprendizaje y comunidad para acompañar ese recorrido.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/kowi" className="kowi-gold-btn rounded-full px-7 py-3 font-semibold">Empezar con Kowi ↗</Link><a href="#ecosistema" className="rounded-full border border-white/25 px-7 py-3">Ver el ecosistema ↓</a></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 md:px-10" id="ecosistema"><p className="kowi-eyebrow">SEIS CAMINOS · UNA VISIÓN</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight md:text-5xl">Elige dónde quieres empezar.</h2><p className="mt-5 max-w-3xl text-[#bdc4cf]">Cada espacio responde a una necesidad distinta. Su estado indica lo que puedes usar ahora y lo que seguimos diseñando.</p><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{areas.map((area,i) => <Link key={area.name} href={area.href} className="cosmos-tile group flex min-h-72 flex-col rounded-3xl p-7"><div className="flex items-start justify-between gap-4"><span className="text-sm text-[#e8b37b]">0{i+1} / KOWI</span><span className="rounded-full border border-[#e8b37b]/30 px-3 py-1 text-xs text-[#e8b37b]">{area.state}</span></div><h3 className="mt-8 text-2xl font-semibold">{area.name}</h3><p className="mt-3 flex-1 leading-relaxed text-[#bdc4cf]">{area.text}</p><span className="mt-8 text-sm font-semibold text-[#e8b37b] group-hover:underline">Explorar ↗</span></Link>)}</div></section>
  <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="kowi-eyebrow">NUESTRA FORMA DE TRABAJAR</p><h2 className="mt-4 text-4xl font-semibold">De la intención a una acción medible.</h2><p className="mt-6 leading-relaxed text-[#bdc4cf]">La tecnología puede sugerir, organizar y acelerar. Las personas deciden los objetivos, validan los resultados y autorizan las acciones sensibles.</p></div><ol className="grid gap-4 sm:grid-cols-2">{[['Escuchar','Entender qué quieres cambiar y qué recursos tienes.'],['Diseñar','Transformar la intención en fases y pasos concretos.'],['Actuar','Usar agentes y herramientas con supervisión cuando corresponde.'],['Aprender','Revisar avances y ajustar el plan con información real.']].map(([title,description],i) => <li className="cosmos-panel rounded-2xl p-6" key={title}><span className="text-sm text-[#e8b37b]">0{i+1}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#bdc4cf]">{description}</p></li>)}</ol></div></section>
  <section className="mx-auto flex max-w-7xl flex-wrap items-end justify-between gap-8 px-5 py-20 md:px-10"><div className="max-w-2xl"><p className="kowi-eyebrow">CONVERSACIÓN ABIERTA</p><h2 className="mt-4 text-4xl font-semibold">¿Quieres construir con Kowi?</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">Si tienes una propuesta de colaboración, educación o impacto, escríbenos. Evaluaremos cada posibilidad según el proyecto y su etapa real.</p></div><a href="mailto:info@kowi.one?subject=Colaborar%20con%20KOWI" className="kowi-gold-btn rounded-full px-7 py-3 font-semibold">Escribir a Kowi ↗</a></section>
  <footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 border-t border-white/10 px-5 py-8 text-sm text-[#aeb6c4] md:px-10"><Link href="/">← Volver al inicio</Link><div className="flex gap-5"><Link href="/fundacion">Fundación</Link><Link href="/privacidad">Privacidad</Link></div></footer>
</main>; }
