'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import InstallKowi from '@/components/InstallKowi';
import {api} from '@/lib/api';
import {organizationSchema} from '@/lib/organization-schema';
import {businessTools,businessUrl,chooseOrganization,type WorkspaceOrganization} from '@/lib/business-workspace';
type Overview={organization:WorkspaceOrganization;role:string;verifiedAccount:boolean;counts:Record<string,number>;agents:{id:string;name:string;status:string;synthetic:boolean;configured:boolean;verified:boolean;active:boolean}[];tasks:{id:string;title:string;due_at:string|null}[];appointments:{id:string;title:string;starts_at:string;status:string}[];observedAt:string};
const preference='kowi.business.organization';
export default function BusinessWorkspace({onSignOut}:{onSignOut:()=>Promise<void>}){
 const [orgs,setOrgs]=useState<WorkspaceOrganization[]>([]),[org,setOrg]=useState(''),[name,setName]=useState('');
 const [overview,setOverview]=useState<Overview|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let live=true;api<WorkspaceOrganization[]>('/api/organizations').then(rows=>{if(!live)return;setOrgs(rows);let stored=null;try{stored=localStorage.getItem(preference);}catch{}setOrg(chooseOrganization(rows,new URLSearchParams(window.location.search).get('organization_id'),stored));}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 useEffect(()=>{setOverview(null);if(!org)return;let live=true;setLoading(true);setError('');try{localStorage.setItem(preference,org);}catch{}
 api<Overview>('/api/business/workspace?organization_id='+org).then(data=>{if(live)setOverview(data);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[org,refresh]);
 async function create(event:React.FormEvent){event.preventDefault();if(busy)return;const parsed=organizationSchema.safeParse({name});if(!parsed.success){setError('Escribe el nombre real de tu empresa.');return;}setBusy(true);setError('');
 try{const row=await api<WorkspaceOrganization>('/api/organizations',{method:'POST',body:JSON.stringify(parsed.data)});setOrgs(old=>[...old,row]);setOrg(row.id);setName('');}catch(e){setError(e instanceof Error?e.message:'No se pudo crear.');}finally{setBusy(false);}}
 async function signOut(){setBusy(true);setError('');try{await onSignOut();try{localStorage.removeItem(preference);}catch{}}catch(e){setError(e instanceof Error?e.message:'No se pudo cerrar la sesión.');setBusy(false);}}
 const path=(route:string,entity?:string)=>businessUrl(route,org,entity);
 const configured=overview?.agents.some(a=>a.configured),verified=overview?.agents.some(a=>a.verified),active=overview?.agents.some(a=>a.active);
 const actorCanConfigure=overview&&['owner','admin','configurator'].includes(overview.role);
 const format=(value:string)=>new Intl.DateTimeFormat('es',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
 return <main className="kowi-shell min-h-screen px-5 pb-28 pt-6 text-white md:px-10"><div className="mx-auto max-w-6xl space-y-7">
 <header className="flex flex-wrap items-center justify-between gap-4"><Link href="/business/app" className="text-xl font-semibold text-[#e8b37b]">KOWI Business</Link><div className="flex flex-wrap gap-4"><Link href="/app" className="underline">Ecosistema KOWI</Link><button disabled={busy} onClick={()=>void signOut()} className="underline">Cerrar sesión</button></div></header>
 <section><p className="text-sm uppercase tracking-widest text-[#e8b37b]">TU NEGOCIO · TU CONTROL</p><h1 className="mt-3 text-3xl font-semibold md:text-5xl">Gestiona tu negocio con KOWI</h1><p className="mt-4 text-[#abc3b4]">Contactos, oportunidades, agenda y tareas en un mismo espacio. La IA amplía tu capacidad; tú autorizas las acciones sensibles.</p></section>
 {error&&<div role="alert" aria-live="assertive" className="rounded-xl border-2 border-red-400 bg-red-950/80 p-4 text-red-100 shadow-lg"><p className="font-bold">⚠ No se pudo completar la operación</p><p className="mt-1">{error}</p><p className="mt-2 text-sm">Comprueba tu sesión, la verificación del correo y el límite de 20 empresas por cuenta. Si continúa, contacta con soporte.</p></div>}{loading&&<p role="status">Consultando tu negocio…</p>}
 {!!orgs.length&&<label className="block">Empresa<select aria-label="Empresa" value={org} disabled={busy||loading} onChange={e=>setOrg(e.target.value)} className="mt-2 block w-full rounded-xl bg-[#102b22] p-3">{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
 {!loading&&!orgs.length&&!error&&<section className="glass rounded-2xl p-6"><h2 className="text-2xl">Crea tu primera empresa</h2><p className="mt-3">Tu información empresarial se guardará en su propio espacio.</p></section>}
 <details className="glass rounded-2xl p-5" open={!orgs.length}><summary className="cursor-pointer font-semibold">{orgs.length?'Añadir otra empresa':'Registrar mi negocio'}</summary><form onSubmit={create} className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="flex-1">Nombre de la empresa<input required minLength={2} maxLength={120} value={name} disabled={busy} onChange={e=>setName(e.target.value)} className="mt-2 block w-full rounded-xl bg-[#102b22] p-3"/></label><button disabled={busy||loading} className="rounded-xl bg-[#e8b37b] px-5 py-3 font-semibold text-black disabled:opacity-50">Crear empresa</button></form></details>
 {overview&&<>
 <section className="glass rounded-2xl p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl">{overview.organization.name}</h2><button disabled={busy||loading} onClick={()=>setRefresh(n=>n+1)} className="underline">Actualizar negocio</button></div><p className="mt-3 text-sm">Permiso: {overview.role}. Consulta: {format(overview.observedAt)}.</p>
 {!overview.verifiedAccount&&<p className="mt-3">Verifica tu cuenta antes de configurar agentes o autorizar órdenes.</p>}
 {overview.agents.some(a=>a.synthetic)&&<p className="mt-3 rounded-xl border border-[#e8b37b]/40 p-3 text-sm">Hay instalaciones marcadas como prueba sintética. Sus estados no acreditan una conversación IA ni clientes reales.</p>}
 <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3">{[['contacts','Contactos'],['leads','Leads'],['opportunities','Oportunidades'],['appointments','Citas registradas'],['tasks','Tareas registradas'],['conversations','Conversaciones privadas']].map(([key,label])=><article key={key} className="rounded-xl border border-white/15 p-4"><p className="text-sm">{label}</p><p className="mt-2 text-3xl">{overview.counts[key]}</p></article>)}</div><p className="mt-3 text-sm text-[#abc3b4]">Conteos de registros de esta empresa. No representan ingresos, ventas ni reservas externas verificadas.</p></section>
 <section className="glass rounded-2xl p-6"><h2 className="text-2xl">Pon tu agente a trabajar</h2><ol className="mt-5 grid gap-4 sm:grid-cols-3">{[
 [configured?'Configuración guardada':'1. Configura tu agente','Productos, servicios y respuestas confirmadas.',path('/business/agents')],
 [verified?'Conversación IA verificada':'2. Prueba una conversación','Guarda una respuesta real y su evidencia.',path('/business/agent-chat')],
 [active?'Agente privado activo':'3. Activa y dirige','Activa desde la conversación; después revisa órdenes y aval.',active?path('/business/director'):path('/business/agent-chat')]
 ].map(([title,body,url])=><li key={title} className="rounded-xl border border-white/20 p-4"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm text-[#abc3b4]">{body}</p><Link href={url} className="mt-4 inline-block underline">Abrir ↗</Link></li>)}</ol>{!actorCanConfigure&&<p className="mt-4 text-sm">Tu rol no permite configurar el agente. Solicita esa operación al propietario o administrador.</p>}</section>
 <nav aria-label="Gestión del negocio" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{businessTools.map(tool=><Link key={tool.title} href={path(tool.path,'entity' in tool?tool.entity:undefined)} className="glass rounded-2xl p-5 hover:border-[#e8b37b]/60"><h2 className="text-xl">{tool.title} ↗</h2><p className="mt-3 text-sm text-[#abc3b4]">{tool.description}</p></Link>)}</nav>
 <div className="grid gap-5 md:grid-cols-2"><section className="glass rounded-2xl p-5"><h2 className="text-2xl">Próximas citas</h2><p className="mt-3 text-sm">Agenda local: no acredita sincronización con Google Calendar ni disponibilidad.</p>{!overview.appointments.length&&<p className="mt-4">No hay próximas citas registradas.</p>}<ul className="mt-4 space-y-3">{overview.appointments.map(a=><li key={a.id} className="rounded-xl border border-white/15 p-3"><p>{a.title}</p><p className="mt-2 text-sm">{format(a.starts_at)} · {a.status==='proposed'?'Propuesta':'Confirmada localmente'}</p></li>)}</ul><Link className="mt-4 inline-block underline" href={path('/business/crm-org','appointments')}>Abrir agenda ↗</Link></section>
 <section className="glass rounded-2xl p-5"><h2 className="text-2xl">Trabajo pendiente</h2>{!overview.tasks.length&&<p className="mt-4">No hay tareas abiertas registradas.</p>}<ul className="mt-4 space-y-3">{overview.tasks.map(t=><li key={t.id} className="rounded-xl border border-white/15 p-3"><p>{t.title}</p><p className="mt-2 text-sm">{t.due_at?format(t.due_at):'Sin fecha asignada'}</p></li>)}</ul><Link className="mt-4 inline-block underline" href={path('/business/crm-org','tasks')}>Abrir tareas ↗</Link></section></div>
 <section className="glass rounded-2xl p-5"><h2 className="text-2xl">Correo y canales</h2><p className="mt-3">La prueba de correo requiere una conversación guardada y autorización expresa. Google Calendar, WhatsApp y lectura del buzón necesitan conexión y verificación independientes.</p><Link href="/test-email" className="mt-4 inline-block underline">Preparar prueba de correo controlada ↗</Link></section>
 </>}
 <InstallKowi business/>
 <footer className="flex flex-wrap gap-5 py-4 text-sm"><Link href="/privacidad">Privacidad y uso de IA</Link><Link href="/news">News</Link><Link href="/business">Conocer KOWI Business</Link></footer>
 {!!org&&<nav aria-label="Accesos rápidos del negocio" className="fixed inset-x-0 bottom-0 z-50 flex justify-center gap-1 border-t border-white/20 bg-[#071612] px-2 pb-[max(.75rem,env(safe-area-inset-bottom))] pt-3 text-sm"><Link href="/business/app" className="rounded-xl px-3 py-2">Inicio</Link><Link href={path('/business/crm-org','contacts')} className="rounded-xl px-3 py-2">CRM</Link><Link href={path('/business/agent-chat')} className="rounded-xl px-3 py-2">IA</Link><Link href={path('/business/crm-org','appointments')} className="rounded-xl px-3 py-2">Agenda</Link><Link href={path('/business/director')} className="rounded-xl px-3 py-2">Director</Link></nav>}
 </div></main>;
}
