'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import OrganizationSetup from '@/components/OrganizationSetup';
import { businessConfigSchema, type BusinessConfig } from '@/lib/business-schema';

type Lead = { id:string; name:string; contact:string; status:string; next_action:string; notes:string; updated_at:string };
type Conversation = { id:string; title:string; agent:string };
type Turn = { id:string; user_message:string; response:string };
const initial: BusinessConfig = { name:'', sector:'comercio', description:'', contact:'', escalation:'', services:[], hours:'', team:'', faq:[], policies:'', tone:'Cercano y claro', automaticActions:['answer_faq','recommend','qualify'] };
const examples: Record<string,BusinessConfig> = {
  belleza: { ...initial, name:'Estudio Raíz (DEMO)', sector:'belleza', description:'Peluquería de barrio con atención personalizada.', hours:'Lunes a viernes, 10:00–19:00.', services:[{name:'Corte',price:'desde 20 €'},{name:'Color',price:'bajo presupuesto'}], faq:[{question:'¿Puedo reservar?',answer:'El equipo confirma disponibilidad antes de cerrar la cita.'}], escalation:'Derivar reservas y precios finales a recepción.' },
  salud: { ...initial, name:'Clínica Sonrisa (DEMO)', sector:'salud', description:'Consulta dental de demostración. Sin asesoramiento clínico.', hours:'Lunes a viernes, 9:00–18:00.', services:[{name:'Consulta inicial',price:'Consultar al equipo'}], faq:[{question:'¿Podéis diagnosticar por chat?',answer:'No. Un profesional debe valorar cada caso.'}], escalation:'Derivar consultas clínicas y citas a personal sanitario. No solicitar datos de salud.' },
  inmobiliaria: { ...initial, name:'Vivienda Norte (DEMO)', sector:'inmobiliaria', description:'Promotora inmobiliaria de demostración.', hours:'Lunes a viernes, 9:00–18:00.', services:[{name:'Información sobre viviendas',price:'Consultar disponibilidad'}], faq:[{question:'¿Puedo visitar una vivienda?',answer:'El equipo confirma las visitas y disponibilidad.'}], escalation:'Derivar ofertas, disponibilidad y visitas a un asesor.' },
};
const field='mt-1 w-full rounded-xl border border-white/15 bg-[#102b22] p-3 text-white outline-none focus:border-[#e8b37b]';
export default function BusinessConsole({onSignOut}:{onSignOut:()=>Promise<void>}) {
  const [config,setConfig]=useState<BusinessConfig>(initial);
  const [services,setServices]=useState(''); const [faq,setFaq]=useState('');
  const [saved,setSaved]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  const [leads,setLeads]=useState<Lead[]>([]); const [conversations,setConversations]=useState<Conversation[]>([]);
  const [conversation,setConversation]=useState<string|null>(null); const [turns,setTurns]=useState<Turn[]>([]); const [message,setMessage]=useState('');
  const [lead,setLead]=useState({name:'',contact:'',notes:'',next_action:'',source:'manual',consent:false});
  const demoScenarios=[{title:'Peluquería',ask:'Cliente: “Quiero corte y color el viernes por la tarde.”',result:'KOWI identifica servicios, cualifica la necesidad y prepara lead + siguiente acción.'},{title:'Clínica dental',ask:'Paciente: “Quiero una primera consulta, ¿tenéis hueco?”',result:'KOWI informa con datos confirmados y deriva cita; no diagnostica ni inventa disponibilidad.'},{title:'Inmobiliaria',ask:'Comprador: “Busco vivienda de 3 habitaciones cerca de Madrid.”',result:'KOWI pregunta criterios, cualifica la oportunidad y prepara seguimiento para el asesor.'}];
  const load=useCallback(async()=>{
    const [profile, contacts, chats]=await Promise.all([
      api<{config:BusinessConfig}|null>('/api/business/profile'), api<Lead[]>('/api/business/leads'), api<Conversation[]>('/api/conversations')]);
    if(profile?.config){const parsed=businessConfigSchema.safeParse(profile.config); if(parsed.success){setConfig(parsed.data);setSaved(true);setServices(parsed.data.services.map(s=>`${s.name} | ${s.price}`).join('\n'));setFaq(parsed.data.faq.map(f=>`${f.question} | ${f.answer}`).join('\n'));}}
    setLeads(contacts); setConversations(chats.filter(c=>c.agent==='business'));
  },[]);
  useEffect(()=>{load().catch(()=>setNotice('No se pudo cargar el panel. Recarga la página.'));},[load]);
  function update<K extends keyof BusinessConfig>(key:K,value:BusinessConfig[K]){setConfig(c=>({...c,[key]:value}));setSaved(false);}
  function chooseExample(key:string){const sample=examples[key];setConfig(sample);setServices(sample.services.map(s=>`${s.name} | ${s.price}`).join('\n'));setFaq(sample.faq.map(f=>`${f.question} | ${f.answer}`).join('\n'));setSaved(false);setNotice('Ejemplo ficticio cargado. Guarda la configuración para probarlo.');}
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'No se pudo completar.');}finally{setBusy(false);}}
  const lines=(value:string)=>value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>x.split('|',2).map(v=>v.trim()));
  async function save(e:React.FormEvent){e.preventDefault();await run(async()=>{const next={...config,services:lines(services).map(([name,price])=>({name,price:price||''})),faq:lines(faq).map(([question,answer])=>({question,answer:answer||''}))};const parsed=businessConfigSchema.safeParse(next);if(!parsed.success)throw new Error('Revisa los campos y sus límites de longitud.');const result=await api<{config:BusinessConfig}>('/api/business/profile',{method:'PUT',body:JSON.stringify(parsed.data)});setConfig(result.config);setSaved(true);setNotice('Agente configurado. Ya puedes probar una conversación real.');});}
  async function send(e:React.FormEvent){e.preventDefault();if(!saved||!message.trim())return;await run(async()=>{let id=conversation;if(!id){const created=await api<Conversation>('/api/conversations',{method:'POST',body:JSON.stringify({agent:'business'})});id=created.id;setConversation(id);setConversations(prev=>[created,...prev]);}const text=message.trim();const result=await api<{response:string}>('/api/chat',{method:'POST',body:JSON.stringify({userMessage:text,conversationId:id,requestId:crypto.randomUUID()})});setTurns(prev=>[...prev,{id:crypto.randomUUID(),user_message:text,response:result.response}]);setMessage('');setNotice('Respuesta guardada en tu historial. No se ha enviado a clientes.');});}
  async function openChat(id:string){await run(async()=>{const result=await api<{turns:Turn[]}>(`/api/conversations/${id}`);setConversation(id);setTurns(result.turns);});}
  async function addLead(e:React.FormEvent){e.preventDefault();await run(async()=>{await api('/api/business/leads',{method:'POST',body:JSON.stringify(lead)});setLead({name:'',contact:'',notes:'',next_action:'',source:'manual',consent:false});await load();setNotice('Contacto registrado. Ninguna comunicación se ha enviado.');});}
  return <main className="kowi-shell min-h-screen text-[#eef8ef]"><div className="kowi-grid pointer-events-none fixed inset-0 opacity-30"/>
    <header className="relative z-10 border-b border-white/10 px-6 py-5"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><Link href="/business" className="font-bold tracking-[.23em]">KOWI BUSINESS</Link><nav className="flex flex-wrap gap-4 text-sm"><a href="#configurar">Configurar</a><a href="#probar">Probar</a><a href="#contactos">Contactos</a><Link href="/business/agent">Acciones</Link><Link href="/proyectos">Proyectos</Link><button onClick={()=>run(onSignOut)} className="underline">Salir</button></nav></div></header>
    <div className="relative z-10 mx-auto max-w-7xl space-y-8 px-6 py-12"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e8b37b]">Panel del propietario · canal web privado</p><h1 className="mt-3 text-4xl font-semibold">Tu empresa y su agente</h1><p className="mt-3 text-[#a9c1b3]">Una empresa por cuenta en este piloto. Tus clientes no ven este panel. Revisa todas las respuestas antes de usarlas fuera de Kowi.</p></div>
    {notice&&<p role="status" className="rounded-xl border border-[#e8b37b]/30 bg-[#e8b37b]/10 p-4">{notice}</p>}
    <section className="glass rounded-[1.7rem] p-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e8b37b]">DEMO COMERCIAL GUIADA</p><h2 className="mt-2 text-2xl font-semibold">Mira cómo KOWI convierte una conversación en una oportunidad</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{demoScenarios.map(d=><article key={d.title} className="rounded-xl border border-white/10 bg-white/5 p-4"><h3 className="font-semibold">{d.title}</h3><p className="mt-3 text-sm">{d.ask}</p><p className="mt-3 text-xs text-[#a9c1b3]">{d.result}</p></article>)}</div><div className="mt-5 flex flex-wrap gap-3"><a href="#probar" className="rounded-full bg-[#e8b37b] px-5 py-3 font-semibold text-[#17121a]">Simular conversación ↓</a><Link href="/business/agent" className="rounded-full border border-white/20 px-5 py-3">Ver CRM y aprobaciones ↗</Link></div></section>\n    <OrganizationSetup/>
    <section id="configurar" className="glass rounded-[1.7rem] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl font-semibold">1. Configura tu empresa</h2><span className="text-sm text-[#e8b37b]">{saved?'Configuración guardada':'Pendiente de guardar'}</span></div><div className="mt-5 flex flex-wrap gap-2">{Object.entries({belleza:'Peluquería',salud:'Clínica dental',inmobiliaria:'Promotora inmobiliaria'}).map(([key,label])=><button type="button" key={key} onClick={()=>chooseExample(key)} className="rounded-full border border-white/20 px-4 py-2 text-sm">Cargar demo: {label}</button>)}</div>
      <form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2"><label>Nombre del negocio<input required maxLength={120} value={config.name} onChange={e=>update('name',e.target.value)} className={field}/></label><label>Sector<select value={config.sector} onChange={e=>update('sector',e.target.value as BusinessConfig['sector'])} className={field}>{Object.entries({comercio:'Comercio',belleza:'Peluquería y estética',salud:'Clínica o consulta',inmobiliaria:'Inmobiliaria',taller:'Taller',restauracion:'Restauración',profesional:'Profesional',pyme:'Pyme',otro:'Otro'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      <label>Descripción<textarea maxLength={1200} value={config.description} onChange={e=>update('description',e.target.value)} className={field}/></label><label>Datos de contacto públicos<textarea maxLength={300} value={config.contact} onChange={e=>update('contact',e.target.value)} className={field}/></label><label>Horarios<textarea maxLength={700} value={config.hours} onChange={e=>update('hours',e.target.value)} className={field}/></label><label>Equipo disponible<textarea maxLength={700} value={config.team} onChange={e=>update('team',e.target.value)} className={field}/></label><label>Servicios y precios (uno por línea: servicio | precio)<textarea rows={3} maxLength={5000} value={services} onChange={e=>{setServices(e.target.value);setSaved(false);}} className={field}/></label><label>Preguntas frecuentes (pregunta | respuesta)<textarea rows={3} maxLength={15000} value={faq} onChange={e=>{setFaq(e.target.value);setSaved(false);}} className={field}/></label><label>Tono<textarea maxLength={300} value={config.tone} onChange={e=>update('tone',e.target.value)} className={field}/></label><label>Cuándo derivar a una persona<textarea maxLength={700} value={config.escalation} onChange={e=>update('escalation',e.target.value)} className={field}/></label><label className="md:col-span-2">Políticas y límites<textarea maxLength={1500} value={config.policies} onChange={e=>update('policies',e.target.value)} className={field}/></label><p className="text-sm text-[#a9c1b3] md:col-span-2">Permisos de demo: responder sobre hechos confirmados, recomendar servicios y hacer preguntas. Citas, mensajes externos, pagos, cambios sensibles y borrados requieren autorización humana y un canal verificado.</p><button disabled={busy} className="rounded-full bg-[#e8b37b] px-6 py-3 font-semibold text-[#17121a] disabled:opacity-50">Guardar configuración</button></form>
    </section>
    <section id="probar" className="glass rounded-[1.7rem] p-6"><h2 className="text-2xl font-semibold">2. Prueba una conversación real</h2><p className="mt-2 text-sm text-[#a9c1b3]">La IA responde con los datos guardados de tu negocio. Conversación privada; ningún mensaje sale por WhatsApp o correo.</p><div className="mt-4 flex flex-wrap gap-2">{conversations.map(c=><button key={c.id} onClick={()=>openChat(c.id)} className="rounded-full border border-white/15 px-3 py-2 text-xs">{c.title}</button>)}<button onClick={()=>{setConversation(null);setTurns([]);}} className="rounded-full border border-white/15 px-3 py-2 text-xs">Nueva conversación</button></div><div className="mt-5 max-h-96 space-y-3 overflow-y-auto rounded-xl bg-[#091d17] p-4" role="log" aria-label="Conversación">{turns.length===0&&<p className="text-[#8ca796]">Pregunta como cliente: “¿Cuánto cuesta el servicio y puedo reservar?”</p>}{turns.map(t=><div key={t.id} className="space-y-2"><p className="ml-auto max-w-[80%] rounded-xl bg-[#e8b37b] p-3 text-[#17121a]">{t.user_message}</p><p className="max-w-[85%] whitespace-pre-wrap rounded-xl bg-white/10 p-3">{t.response}</p></div>)}</div><form onSubmit={send} className="mt-4 flex flex-col gap-3 md:flex-row"><input required maxLength={2000} disabled={busy||!saved} value={message} onChange={e=>setMessage(e.target.value)} placeholder={saved?'Escribe una pregunta de un cliente…':'Guarda primero tu empresa'} className={field}/><button disabled={busy||!saved} className="rounded-xl bg-[#e8b37b] px-6 py-3 font-semibold text-[#17121a] disabled:opacity-50">Enviar</button></form></section>
    <section id="contactos" className="glass rounded-[1.7rem] p-6"><h2 className="text-2xl font-semibold">3. Contactos y solicitudes</h2><p className="mt-2 text-sm text-[#a9c1b3]">Registro manual en el piloto. La prueba de chat no crea contactos automáticamente.</p><form onSubmit={addLead} className="mt-5 grid gap-3 md:grid-cols-2"><label>Nombre<input required maxLength={100} className={field} value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})}/></label><label>Contacto<input maxLength={120} className={field} value={lead.contact} onChange={e=>setLead({...lead,contact:e.target.value})}/></label><label>Origen<select className={field} value={lead.source} onChange={e=>setLead({...lead,source:e.target.value})}><option value="manual">Manual</option><option value="web">Web</option><option value="telefono">Teléfono</option></select></label><label>Siguiente acción<input maxLength={500} className={field} value={lead.next_action} onChange={e=>setLead({...lead,next_action:e.target.value})}/></label><label className="md:col-span-2">Notas<input maxLength={1000} className={field} value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})}/></label><label className="text-sm md:col-span-2"><input type="checkbox" checked={lead.consent} onChange={e=>setLead({...lead,consent:e.target.checked})}/> El contacto ha autorizado comunicaciones de seguimiento (si no, solo registro interno).</label><button disabled={busy} className="rounded-full bg-[#e8b37b] px-6 py-3 font-semibold text-[#17121a]">Registrar solicitud</button></form><div className="mt-5 grid gap-3 md:grid-cols-2">{leads.map(l=><article key={l.id} className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold">{l.name}</h3><p className="text-sm text-[#a9c1b3]">{l.contact||'Sin contacto'} · {l.status}</p><p className="mt-2 text-sm">Siguiente: {l.next_action||'Pendiente de definir'}</p></article>)}</div><Link href="/business/agent" className="mt-5 inline-block text-[#e8b37b] underline">Abrir CRM y aprobaciones →</Link></section>
    <section className="glass rounded-[1.7rem] p-6"><h2 className="text-2xl font-semibold">4. Solicita activar canales</h2><p className="mt-2 text-[#a9c1b3]">Web privado activo. Email, WhatsApp, calendario y CRM externo requieren credenciales, permisos y verificación de extremo a extremo. No se activan desde esta demo.</p><a href="mailto:info@kowi.one?subject=Activaci%C3%B3n%20de%20canales%20KOWI%20Business" className="mt-4 inline-block rounded-full border border-[#e8b37b]/30 px-5 py-3">Solicitar activación por correo ↗</a></section>
    </div></main>;
}
