import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Fundación KOWI | Visión en desarrollo', description: 'Una iniciativa en diseño para ampliar el acceso a educación, conocimiento y oportunidades a través de proyectos con impacto.' };

export default function Foundation() { return <main className="kowi-cosmos min-h-screen">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-7 md:px-10"><Link href="/" className="inline-flex items-center gap-3 text-[#e8b37b]"><span className="kowi-emblem" aria-hidden="true"/><span className="font-semibold tracking-[.28em]">KOWI</span></Link><Link href="/organizacion" className="text-sm text-[#c6c9d0]">La organización ↗</Link></header>
  <section className="border-y border-white/10 bg-[radial-gradient(circle_at_76%_25%,#b57b4b29,transparent_38%),linear-gradient(130deg,#142339,#060b16_65%)] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">FUNDACIÓN KOWI · INICIATIVA EN DESARROLLO</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[1.08] tracking-tight md:text-7xl">El conocimiento crece cuando <span className="text-[#e8b37b]">se comparte.</span></h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-[#c5cad3]">Imaginamos una iniciativa capaz de acercar aprendizaje, herramientas y acompañamiento a personas con ideas que pueden mejorar su entorno. Esta es la visión que guía el diseño; todavía no es un programa abierto.</p><a href="#proposito" className="mt-9 inline-flex rounded-full border border-white/30 px-6 py-3">Conocer el propósito ↓</a></div></section>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[.75fr_1.25fr] md:px-10" id="proposito"><div><p className="kowi-eyebrow">PROPÓSITO</p><h2 className="mt-4 text-4xl font-semibold leading-tight">Que una oportunidad de aprender se convierta en capacidad de actuar.</h2></div><div className="space-y-6 text-lg leading-relaxed text-[#bdc4cf]"><p>Queremos explorar proyectos educativos y sociales que partan de necesidades reales, integren saberes profesionales y permitan medir su utilidad. Kowi puede ayudar a estructurar las ideas y hacer visibles los próximos pasos.</p><p>Nos interesan ámbitos como educación, bienestar y desarrollo local. Cualquier colaboración con instituciones, especialistas o comunidades dependerá de acuerdos concretos y de las garantías adecuadas.</p></div></section>
  <section className="border-y border-white/10 bg-[#0a1120] px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><p className="kowi-eyebrow">PRINCIPIOS PARA DISEÑARLA</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[['Escuchar primero','Definir la necesidad junto a quienes conocen el contexto antes de proponer soluciones.'],['Construir con responsabilidad','Contar con experiencia profesional, consentimiento y revisión humana en ámbitos sensibles.'],['Medir para mejorar','Plantear objetivos verificables y revisar resultados antes de ampliar cualquier iniciativa.']].map(([title,description],i) => <article key={title} className="cosmos-panel rounded-3xl p-7"><span className="text-sm text-[#e8b37b]">0{i+1} / PRINCIPIO</span><h3 className="mt-8 text-2xl font-semibold">{title}</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">{description}</p></article>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:grid-cols-2 md:px-10"><div><p className="kowi-eyebrow">ESTADO ACTUAL</p><h2 className="mt-4 text-4xl font-semibold">La visión está abierta. La estructura se está definiendo.</h2><p className="mt-5 leading-relaxed text-[#bdc4cf]">Fundación KOWI es por ahora el nombre de una iniciativa en desarrollo. No hay constitución jurídica verificada como fundación ni programas, financiación, convenios o convocatorias abiertos anunciados desde esta página. Antes de recibir donaciones o lanzar proyectos se definirán la estructura legal y sus condiciones.</p></div><aside className="cosmos-panel rounded-3xl p-8"><h3 className="text-2xl font-semibold">Propón una conversación</h3><p className="mt-4 leading-relaxed text-[#bdc4cf]">Si trabajas en educación, investigación, salud o una comunidad local y quieres compartir un reto o conocimiento, puedes escribirnos. El enlace abre tu aplicación de correo; esta página no registra postulaciones.</p><a href="mailto:info@kowi.one?subject=Iniciativa%20Fundaci%C3%B3n%20KOWI" className="kowi-gold-btn mt-8 inline-flex rounded-full px-6 py-3 font-semibold">Contactar ↗</a><p className="mt-5 text-xs text-[#aeb6c4]">No envíes información clínica ni datos sensibles por correo.</p></aside></section>
  <section className="border-t border-white/10 px-5 py-14 md:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><p className="max-w-xl text-lg text-[#c5cad3]">Mientras esta iniciativa toma forma, puedes empezar hoy con una idea en Kowi One.</p><Link href="/kowi" className="rounded-full border border-[#e8b37b]/50 px-6 py-3 text-[#e8b37b]">Abrir Kowi One ↗</Link></div></section>
  <footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 border-t border-white/10 px-5 py-8 text-sm text-[#aeb6c4] md:px-10"><Link href="/">← Volver al inicio</Link><Link href="/privacidad">Privacidad</Link></footer>
</main>; }
