export type KowiAgent = {
  id: string; name: string; role: string; access: 'core'|'pro'; risk: 'low'|'medium'|'high';
  capabilities: string[]; requiresApproval: string[]; availability?: 'proposed';
};

export const kowiAgents: KowiAgent[] = [
  {id:'communications',name:'KOWI Communications',role:'Prepara comunicación corporativa, imagen, marca, actualidad y comunidad con fuentes verificables y criterio Human-First. El director crea tareas editoriales bajo aval; no hay publicación autónoma de IA.',access:'pro',risk:'high',availability:'proposed',capabilities:['source_verification','editorial_planning','brand_consistency','community_content','impact_review'],requiresApproval:['publish','external_message','campaign','personal_data_use']},
  {id:'director',name:'KOWI Director',role:'Recibe órdenes, prepara planes delimitados y crea tareas y grupos privados con aval del propietario verificado. No ejecuta comunicaciones externas ni alcanza automáticamente el objetivo.',access:'pro',risk:'high',capabilities:['bounded_planning','owner_approval','internal_task_execution','midday_decisions'],requiresApproval:['plan_execution','external_message','permission_change']},
  {id:'global-commercial-director',name:'Global Commercial Director',role:'Prepara mercados, idiomas, propuestas y seguimiento en el CRM universal. La presencia internacional y los envíos requieren validación y autorización específica.',access:'pro',risk:'high',availability:'proposed',capabilities:['market_planning','localized_proposals','consent_review','pipeline_follow_up'],requiresApproval:['external_message','campaign','contract','ad_spend']},
  {id:'orchestrator',name:'KOWI Orchestrator',role:'Comprende la intención y coordina agentes, herramientas y personas.',access:'core',risk:'medium',capabilities:['routing','planning','handoff'],requiresApproval:['external_action','sensitive_change']},
  {id:'business',name:'Business Agent',role:'Atención, cualificación, ventas y seguimiento comercial.',access:'pro',risk:'medium',capabilities:['customer_service','sales','lead_qualification'],requiresApproval:['external_message','booking','crm_write']},
  {id:'crm',name:'CRM Agent',role:'Organiza oportunidades, pipeline y próximas acciones.',access:'pro',risk:'medium',capabilities:['lead_management','pipeline','follow_up'],requiresApproval:['crm_write','external_message']},
  {id:'operations',name:'Operations Agent',role:'Coordina procesos, tareas, incidencias y mejora operativa.',access:'pro',risk:'medium',capabilities:['workflow','tasks','process_improvement'],requiresApproval:['system_write','external_action']},
  {id:'finance',name:'Financial Analyst Agent IA PRO',role:'Analiza ingresos, costes, caja, márgenes, desviaciones y escenarios; genera reportes sin ejecutar movimientos.',access:'pro',risk:'high',capabilities:['analysis','forecasting','reporting'],requiresApproval:['payment','financial_commitment','external_action']},
  {id:'marketing',name:'Marketing Agent IA PRO',role:'Analiza adquisición, conversión y retención; propone campañas, contenido y experimentos medibles.',access:'pro',risk:'medium',capabilities:['campaigns','content','analytics'],requiresApproval:['publish','ad_spend','external_message']},
  {id:'tourism-growth',name:'KOWI Local Tourism Agent',role:'Convierte demanda turística en contenido, leads, reservas, CRM y aprendizaje comercial para negocios locales.',access:'pro',risk:'medium',capabilities:['tourism_content','lead_generation','booking_planning','crm_follow_up','local_growth'],requiresApproval:['external_message','booking','crm_write','public_post']},
  {id:'insights',name:'Performance & Insights Agent',role:'Consolida señales de CRM, finanzas, marketing y operaciones para detectar problemas, mejoras y tendencias.',access:'pro',risk:'low',capabilities:['statistics','anomaly_detection','cross_agent_reporting'],requiresApproval:[]},
  {id:'opportunity-feasibility',name:'Opportunity & Feasibility Agent',role:'Convierte recursos, necesidades y oportunidades en hipótesis verificables antes de comprometer capital.',access:'pro',risk:'medium',capabilities:['opportunity_discovery','feasibility','scenario_design'],requiresApproval:['external_action','financial_commitment']},
  {id:'real-estate-infrastructure',name:'Real Estate & Infrastructure Agent',role:'Estructura análisis de suelo, rehabilitación, construcción, hotelería e infraestructura; no compra ni contrata.',access:'pro',risk:'high',capabilities:['site_analysis','capex_model','development_plan','asset_improvement'],requiresApproval:['property_purchase','contract','construction','debt','financial_commitment']},
  {id:'community-resilience',name:'Community Resilience Agent',role:'Mide necesidades y resiliencia en alimentos, energía, agua, vivienda, empleo y circularidad para priorizar proyectos.',access:'pro',risk:'medium',capabilities:['resource_mapping','resilience_metrics','impact_model'],requiresApproval:['external_action','public_commitment']},
  {id:'projects',name:'Projects Agent',role:'Convierte ideas en objetivos, fases, tareas y evidencia.',access:'core',risk:'low',capabilities:['planning','tasks','progress'],requiresApproval:['external_action']},
  {id:'education',name:'School Agent',role:'Guía aprendizaje aplicado y rutas de capacitación.',access:'core',risk:'low',capabilities:['learning','assessment','guidance'],requiresApproval:[]},
  {id:'foundation-infrastructure',name:'Foundation Infrastructure Agent',role:'Prepara escenarios de inversión, fases, hitos y evidencias para proyectos educativos y sanitarios. Solo propone; no contrata, invierte ni opera.',access:'pro',risk:'high',availability:'proposed',capabilities:['needs_assessment','scenario_planning','milestone_planning','evidence_review'],requiresApproval:['investment','contract','construction','operation','public_transfer','external_message']},
  {id:'foundation-formation',name:'Foundation Formation Agent',role:'Organiza requisitos de constitución, consulta fuentes oficiales sobre ayudas y prepara expedientes y métricas para revisión humana. No presenta solicitudes ni capta fondos.',access:'pro',risk:'high',availability:'proposed',capabilities:['official_source_monitoring','formation_checklist','grant_screening','community_consensus_record','impact_reporting'],requiresApproval:['legal_filing','external_message','grant_application','fundraising','financial_commitment','permission_change']},
  {id:'security',name:'Trust & Security Agent',role:'Evalúa riesgo, permisos, anomalías y cumplimiento antes de actuar.',access:'pro',risk:'high',capabilities:['risk_gate','permissions','audit'],requiresApproval:['permission_change','identity_change','deletion']},
  {id:'identity',name:'Identity Agent',role:'Gestiona consentimiento, credenciales e identidad/voz verificable.',access:'pro',risk:'high',capabilities:['consent','credentials','voice_identity'],requiresApproval:['identity_change','voice_use','revocation']},
];

export const agentById = (id:string) => kowiAgents.find(a=>a.id===id);
