'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
type Org={id:string;name:string};
type Agent={id:string;name:string;status:string;last_verified_at:string|null;config:{synthetic?:boolean}};
type Order={id:string;agent_id:string;kind:string;objective:string;markets:string[];status:string;expires_at:string;plan:{steps:{type:string;title:string}[]}};
type State={orders:Order[];events:{id:string;order_id:string;event:string;evidence:unknown;recorded_at:string}[];reports:{id:string;report_date:string;timezone:string;observed:unknown;interpretation:string;recommendation:string}[];groups:{id:string;name:string;purpose:string}[];memberships:{group_id:string;withdrawn_at:string|null}[];schedule:{timezone:string}|null;role:string;verified:boolean};
const markets=[['national','Nacional (país por definir)'],['europe','Europa'],['asia','Asia'],['africa','África'],['north_america','América del Norte'],['south_america','América del Sur'],['indonesia','Indonesia'],['oceania','Oceanía']];
export default function Director(){
 const [orgs,setOrgs]=useState<Org[]>([]),[org,setOrg]=useState(''),[agents,setAgents]=useState<Agent[]>([]),[agent,setAgent]=useState('');
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
 const [kind,setKind]=useState('operations'),[objective,setObjective]=useState(''),[regions,setRegions]=useState<string[]>([]),[timezone,setTimezone]=useState('Europe/Madrid'),[approval,setApproval]=useState<string|null>(null);
 useEffect(()=>{let live=true;api<Org[]>('/api/organizations').then(data=>{if(live){setOrgs(data);const id=new URLSearchParams(window.location.search).get('organization_id');setOrg(data.find(o=>o.id===id)?.id||data[0]?.id||'');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{setState(null);setAgents([]);setAgent('');setApproval(null);if(!org)return;let live=true;setError('');
 Promise.all([api<State>('/api/director?organization_id='+org),api<{items:Agent[]}>('/api/organization-agents?organization_id='+org)]).then(([data,list])=>{if(live){setState(data);setAgents(list.items);const eligible=list.items.find(a=>a.status==='active'&&a.last_verified_at&&!a.config?.synthetic);setAgent(eligible?.id||'');if(data.schedule)setTimezone(data.schedule.timezone);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[org,refresh]);
 async function act(body:unknown){setBusy(true);setError('');setNotice('');try{await api('/api/director?organization_id='+org,{method:'POST',body:JSON.stringify(body)});setNotice('Operación guardada. Consulta el estado y la evidencia.');setApproval(null);setRefresh(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 const owner=state?.role==='owner'&&state.verified;
 const eligible=agents.filter(a=>a.status==='active'&&a.last_verified_at&&!a.config?.synthetic);
 const labels:Record<string,string>={pending_approval:'Decisión pendiente',approved:'Aval concedido · ejecución pendiente',completed:'Trabajo interno creado',rejected:'Rechazada',cancelled:'Cancelada',expired:'Caducada'};
 return <main className="kowi-shell min-h-screen p-5 text-white md:p-10"><div className="mx-auto max-w-5xl space-y-7">
 <Link href="/app" className="underline">← Mi espacio KOWI</Link><p className="text-sm text-[#e8b37b]">PROPÓSITO HUMANO · EJECUCIÓN CONTROLADA</p><h1 className="text-3xl font-semibold">KOWI Director</h1>
 <p>Da una orden, revisa el plan y decide. El director organiza tareas internas y grupos privados; cada ejecución conserva evidencia. La IA empresarial ayuda a preparar contenido en la conversación autenticada.</p>
 <nav aria-label="Herramientas del director" className="flex flex-wrap gap-4 underline"><Link href="/business/agent-chat">Conversar con IA</Link><Link href="/business/crm-org">Contactos, agenda y tareas</Link><Link href="/test-email">Correo con aprobación</Link><Link href="/business/intelligence">Intelligence</Link></nav>
 {error&&<p role="alert" className="rounded-xl border border-red-300/40 p-4">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!!orgs.length&&<label className="block">Empresa<select className="ml-2 max-w-full rounded-xl bg-[#102b22] p-3" value={org} disabled={busy} onChange={e=>setOrg(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
 {state&&<><section className="glass space-y-4 rounded-2xl p-5"><h2 className="text-2xl">Nueva orden</h2>{!owner&&<p>Solo el propietario verificado puede proponer, aprobar y ejecutar órdenes. Puedes consultar el trabajo de tu empresa.</p>}
 {!eligible.length&&<p>Necesitas un agente activo con una conversación IA validada y configuración real. <Link className="underline" href="/business/agents">Configurar y verificar agente</Link>.</p>}
 <form onSubmit={e=>{e.preventDefault();void act({operation:'propose',request_id:crypto.randomUUID(),agent_id:agent,kind,objective,markets:regions,timezone});}} className="space-y-4">
 <label className="block">Agente responsable<select required className="mt-2 block w-full rounded-xl bg-[#102b22] p-3" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Seleccionar agente validado</option>{eligible.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
 <label className="block">Área<select className="mt-2 block w-full rounded-xl bg-[#102b22] p-3" value={kind} onChange={e=>setKind(e.target.value)}><option value="operations">Dirección y operaciones</option><option value="commercial">Dirección comercial internacional</option><option value="foundation">Grupos de la iniciativa Fundación</option></select></label>
 <label className="block">Orden y resultado esperado<textarea required minLength={5} maxLength={1000} rows={4} className="mt-2 block w-full rounded-xl bg-[#102b22] p-3" value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Describe el objetivo sin incluir datos sensibles ni secretos."/></label>
 {kind==='commercial'&&<fieldset><legend>Mercados a preparar</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{markets.map(([id,name])=><label key={id}><input type="checkbox" checked={regions.includes(id)} onChange={e=>setRegions(e.target.checked?[...regions,id]:regions.filter(r=>r!==id))}/> {name}</label>)}</div><p className="mt-3 text-sm">La selección prepara trabajo. No inicia campañas ni afirma ventas o presencia comercial en estos mercados.</p></fieldset>}
 <label className="block">Zona horaria del informe de las 12:00<input required maxLength={100} className="mt-2 block w-full rounded-xl bg-[#102b22] p-3" value={timezone} disabled={Boolean(state.schedule)} onChange={e=>setTimezone(e.target.value)}/></label>
 <p className="text-sm">La primera orden fija esta zona IANA. El proceso revisa cada cinco minutos durante la hora de las 12:00 locales y guarda un informe diario; no se envía por correo automáticamente.</p>
 <button disabled={busy||!owner||!agent} className="rounded-xl bg-[#e8b37b] px-5 py-3 text-black disabled:opacity-50">Preparar plan para aprobación</button></form></section>
 <section className="space-y-4"><h2 className="text-2xl">Decisiones y aval del propietario</h2>{!state.orders.length&&<p>No hay órdenes registradas.</p>}
 {state.orders.map(order=>{const expired=Date.parse(order.expires_at)<=Date.now()&&['pending_approval','approved'].includes(order.status);return <article className="glass space-y-4 rounded-2xl p-5" key={order.id}><h3 className="text-xl">{order.objective}</h3><p>{expired?'Autorización caducada':labels[order.status]||order.status}</p>{!!order.markets.length&&<p>Mercados: {order.markets.map(id=>markets.find(m=>m[0]===id)?.[1]||id).join(', ')}</p>}<ol className="list-inside list-decimal space-y-2">{order.plan.steps.map((step,i)=><li key={i}>{step.title} {step.type==='group'?'(grupo privado)':'(tarea)'}</li>)}</ol><p className="text-sm">Alcance: crear trabajo interno. No envía correos, reserva citas, importa contactos, publica ni cobra. Crear tareas no demuestra que el objetivo se haya alcanzado.</p>
 {owner&&!expired&&order.status==='pending_approval'&&<><label className="block"><input type="checkbox" checked={approval===order.id} onChange={e=>setApproval(e.target.checked?order.id:null)}/> Doy mi aval a este plan exacto y a su alcance interno.</label><button disabled={busy||approval!==order.id} onClick={()=>void act({operation:'approve',order_id:order.id})} className="rounded-xl border border-[#e8b37b] px-4 py-3 disabled:opacity-50">Aprobar plan</button></>}
 {owner&&!expired&&order.status==='approved'&&<button disabled={busy} onClick={()=>void act({operation:'execute',order_id:order.id})} className="rounded-xl bg-[#e8b37b] px-4 py-3 text-black">Ejecutar trabajo interno aprobado</button>}
 {owner&&['pending_approval','approved'].includes(order.status)&&<button disabled={busy} className="ml-3 rounded-xl border border-white/30 px-4 py-3" onClick={()=>void act({operation:'reject',order_id:order.id})}>Rechazar / retirar aval</button>}
 <details><summary>Action Ledger de esta orden</summary>{state.events.filter(e=>e.order_id===order.id).map(e=><div key={e.id} className="mt-3"><p>{e.event} · {e.recorded_at}</p><pre className="overflow-x-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(e.evidence,null,2)}</pre></div>)}</details></article>;})}</section>
 <section className="glass space-y-4 rounded-2xl p-5"><h2 className="text-2xl">Informe de mediodía</h2>{!state.reports.length&&<p>No hay informes generados. Tras la primera orden, revisa este panel durante la hora de las 12:00 de la zona configurada.</p>}{state.reports.map(r=><article key={r.id}><h3>{r.report_date} · {r.timezone}</h3><p className="mt-3 font-semibold">Datos observados</p><pre className="whitespace-pre-wrap break-all text-sm">{JSON.stringify(r.observed,null,2)}</pre><p className="mt-3 font-semibold">Interpretación</p><p>{r.interpretation}</p><p className="mt-3 font-semibold">Recomendación</p><p>{r.recommendation}</p></article>)}</section>
 <section className="glass space-y-4 rounded-2xl p-5"><h2 className="text-2xl">Grupos Human-First</h2><p>Colaboración voluntaria entre miembros autorizados de esta empresa. Unirse permite gestionar la participación en el grupo; no autoriza publicidad, publicación de datos ni donaciones. La iniciativa de Fundación sigue en desarrollo.</p>{!state.groups.length&&<p>Una orden de Fundación aprobada puede crear tres grupos privados. Nadie queda inscrito automáticamente.</p>}{state.groups.map(g=>{const joined=state.memberships.some(m=>m.group_id===g.id&&!m.withdrawn_at);return <article key={g.id} className="rounded-xl border border-white/20 p-4"><h3 className="text-xl">{g.name}</h3><p className="mt-2">{g.purpose}</p><button disabled={busy||!state.verified} className="mt-3 rounded-xl border border-[#e8b37b] px-4 py-3" onClick={()=>void act({operation:'group_consent',group_id:g.id,join:!joined})}>{joined?'Retirar mi participación':'Acepto participar voluntariamente'}</button></article>;})}</section>
 <button disabled={busy} className="rounded-xl border border-white/30 px-5 py-3" onClick={()=>setRefresh(n=>n+1)}>Actualizar decisiones</button>
 </>}
 <p className="text-sm">Google Calendar y acceso al buzón requieren conectores y permisos del titular. Hoy puedes registrar contactos y citas propuestas en CRM y preparar una prueba de correo controlada. No se leen agendas ni buzones externos desde este director.</p>
 </div></main>;
}
