'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Track = 'ideas' | 'business' | 'agents';
const tracks: Record<Track, { title: string; intro: string; result: string; steps: string[] }> = {
  ideas: { title: 'De la idea al proyecto', intro: 'Convierte una inquietud en una propuesta que se pueda probar.', result: 'Una ficha de proyecto con público, problema, primera prueba y medida de resultado.', steps: ['Describe a quién quieres ayudar y qué problema has observado.', 'Habla con tres personas que vivan ese problema y anota sus respuestas.', 'Diseña una versión pequeña que puedas mostrar en una semana.', 'Elige una señal medible y revisa lo que aprendiste.'] },
  business: { title: 'IA para tu negocio', intro: 'Identifica una tarea repetitiva y mejora el proceso con supervisión.', result: 'Un caso de uso con responsables, límites y una métrica antes y después.', steps: ['Dibuja una tarea de atención, ventas o administración.', 'Mide tiempo y errores del proceso actual.', 'Separa datos públicos de información privada y asigna una persona que revise.', 'Prueba cinco casos ficticios y compara los resultados.'] },
  agents: { title: 'Diseño de agentes', intro: 'Diseña un asistente que ayude sin perder el control humano.', result: 'Un prototipo documentado con instrucciones, casos de prueba y aprobaciones.', steps: ['Define objetivo, usuario y acciones permitidas.', 'Reúne fuentes confiables y ejemplos frecuentes.', 'Decide qué puede consultar el agente y qué requiere aprobación.', 'Evalúa precisión, derivación y privacidad con datos ficticios.'] },
};
const keys: Track[] = ['ideas', 'business', 'agents'];

export default function School() {
  const [track, setTrack] = useState<Track>('ideas');
  const [done, setDone] = useState<Record<Track, number[]>>({ ideas: [], business: [], agents: [] });
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('kowi-school-v1') || '{}');
      if (keys.includes(saved.track)) setTrack(saved.track);
      if (saved.done && typeof saved.done === 'object') setDone(Object.fromEntries(keys.map(key => [key, Array.isArray(saved.done[key]) ? saved.done[key].filter((n: unknown) => Number.isInteger(n) && (n as number) >= 0 && (n as number) < 4) : []])) as Record<Track, number[]>);
    } catch { /* Invalid local data starts a fresh plan. */ }
    setLoaded(true);
  }, []);
  useEffect(() => { if (loaded) localStorage.setItem('kowi-school-v1', JSON.stringify({ track, done })); }, [track, done, loaded]);
  const selected = tracks[track];
  const completed = done[track];
  function toggle(index: number) { setDone(current => ({ ...current, [track]: current[track].includes(index) ? current[track].filter(n => n !== index) : [...current[track], index] })); }
  function download() {
    const content = [`# KOWI School · ${selected.title}`, '', selected.intro, '', `Resultado: ${selected.result}`, '', ...selected.steps.map((step, i) => `${completed.includes(i) ? '[x]' : '[ ]'} ${i + 1}. ${step}`), '', 'Guía abierta de autoaprendizaje. No constituye matrícula, certificado ni formación acreditada.'].join('\n');
    const url = URL.createObjectURL(new Blob([content], { type: 'text/markdown;charset=utf-8' }));
    const a = document.createElement('a'); a.href = url; a.download = `kowi-school-${track}.md`; a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <main className="kowi-cosmos min-h-screen px-5 py-8 sm:px-8"><div className="mx-auto max-w-6xl">
    <nav aria-label="Navegación KOWI" className="flex flex-wrap items-center justify-between gap-4 border-b border-[#e8b37b]/20 pb-6"><Link href="/" className="flex items-center gap-3 font-semibold tracking-[.18em]"><span className="kowi-emblem" aria-hidden="true" />KOWI</Link><div className="flex flex-wrap gap-5 text-sm text-[#c9c8d0]"><Link href="/proyectos" className="hover:text-[#e8b37b]">Proyectos</Link><Link href="/business" className="hover:text-[#e8b37b]">Business</Link><Link href="/kowi" className="hover:text-[#e8b37b]">Kowi One</Link></div></nav>
    <header className="grid gap-8 py-16 lg:grid-cols-[1.3fr_.7fr] lg:items-center"><div><p className="kowi-eyebrow">Kowi School</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight sm:text-6xl">Aprende haciendo. Avanza con evidencia.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#b9bdc9]">Explora una ruta práctica para convertir una idea en proyecto, mejorar tu negocio o diseñar un agente útil. Empieza hoy con una guía abierta y guarda tus avances en este dispositivo.</p><a href="#elige-ruta" className="kowi-gold-btn mt-8 inline-flex rounded-full px-6 py-3 font-semibold">Elegir mi ruta ↓</a></div><aside className="cosmos-panel rounded-3xl p-7"><p className="kowi-eyebrow">Programa en preparación</p><h2 className="mt-4 text-2xl font-semibold">Agentes de IA para atención al cliente de pymes</h2><p className="mt-4 leading-relaxed text-[#b9bdc9]">Piloto propuesto de cuatro semanas y 24 horas: procesos, conversación, prototipo, evaluación y defensa de un caso práctico.</p><p className="mt-5 rounded-xl border border-[#e8b37b]/30 bg-[#e8b37b]/10 p-4 text-sm text-[#e9d6bf]">Todavía no hay fechas, plazas, precio final ni matrícula abiertos. Esta guía gratuita no emite credenciales.</p></aside></header>
    <section id="elige-ruta" className="scroll-mt-8 border-t border-[#e8b37b]/20 py-14" aria-labelledby="ruta-heading"><p className="kowi-eyebrow">Empieza por aquí</p><h2 id="ruta-heading" className="mt-3 text-3xl font-semibold">¿Qué quieres construir?</h2><p className="mt-3 text-[#b9bdc9]">Elige un objetivo. Puedes cambiar de ruta cuando quieras; cada avance se guarda por separado en este navegador.</p><div className="mt-7 grid gap-4 md:grid-cols-3">{keys.map(key => <button key={key} type="button" aria-pressed={track === key} onClick={() => setTrack(key)} className={`rounded-2xl border p-6 text-left transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#e8b37b] ${track === key ? 'border-[#e8b37b] bg-[#e8b37b]/15' : 'border-[#d4aa7c44] bg-[#172236aa] hover:border-[#e8b37b]'}`}><span className="text-xl font-semibold">{tracks[key].title}</span><span className="mt-3 block leading-relaxed text-[#b9bdc9]">{tracks[key].intro}</span></button>)}</div></section>
    <section aria-label="Plan de aprendizaje" className="cosmos-panel mb-16 rounded-3xl p-6 sm:p-9"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="kowi-eyebrow">Tu plan inicial</p><h2 className="mt-2 text-3xl font-semibold">{selected.title}</h2><p className="mt-3 max-w-2xl text-[#b9bdc9]">{selected.result}</p></div><p aria-live="polite" className="rounded-full border border-[#e8b37b]/30 px-4 py-2 text-sm text-[#e8b37b]">{completed.length} de {selected.steps.length} pasos</p></div><div className="mt-8 space-y-3">{selected.steps.map((step, index) => <label key={step} className="flex cursor-pointer items-start gap-4 rounded-xl border border-white/10 bg-white/[.03] p-4 hover:border-[#e8b37b]/50"><input type="checkbox" checked={completed.includes(index)} onChange={() => toggle(index)} className="mt-1 h-5 w-5 accent-[#d8a674]" /><span className={completed.includes(index) ? 'text-[#9ba6a9] line-through' : 'text-[#f4f3f2]'}>{step}</span></label>)}</div><div className="mt-8 flex flex-wrap items-center gap-4"><button type="button" onClick={download} className="kowi-gold-btn rounded-full px-6 py-3 font-semibold">Descargar mi plan</button><Link href="/kowi" className="rounded-full border border-[#e8b37b]/40 px-6 py-3 font-semibold text-[#e8b37b] hover:bg-[#e8b37b]/10">Desarrollarlo con Kowi One ↗</Link></div><p className="mt-5 text-sm text-[#9ba6a9]">Tus marcas se guardan solo en este navegador. Descarga el archivo para conservar tu plan.</p></section>
    <section className="grid gap-8 border-t border-[#e8b37b]/20 py-14 md:grid-cols-2"><div><p className="kowi-eyebrow">Aprendizaje acompañado</p><h2 className="mt-3 text-3xl font-semibold">Práctica, revisión y criterio humano.</h2><p className="mt-5 leading-relaxed text-[#b9bdc9]">El modelo del piloto combina diagnóstico, ejercicios aplicados y un proyecto final revisado por una persona. La IA orienta y aporta comentarios preliminares; la evaluación formal corresponderá a un mentor humano.</p></div><div className="space-y-3">{[['01','Diagnóstico','Define tu punto de partida y objetivo.'],['02','Práctica','Ensaya con ejemplos y entregables.'],['03','Evidencia','Presenta un proyecto y revisa el resultado.']].map(([number,title,detail]) => <div key={number} className="cosmos-tile flex gap-5 rounded-2xl p-5"><span className="font-semibold text-[#e8b37b]">{number}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-[#b9bdc9]">{detail}</p></div></div>)}</div></section>
    <footer className="flex flex-wrap items-center justify-between gap-4 border-t border-[#e8b37b]/20 py-8 text-sm text-[#aab0ba]"><span>© KOWI · School</span><a className="text-[#e8b37b] underline underline-offset-4" href="mailto:info@kowi.one?subject=Inter%C3%A9s%20en%20KOWI%20School">Consultar sobre el futuro piloto</a></footer>
  </div></main>;
}
