begin;
-- KOWI School AI is additive. public.projects is the shared KOWI Projects table.
create table public.school_profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique default auth.uid() references auth.users(id) on delete cascade,goal text not null default '',locale text not null default 'es' check(locale in('es','en')),plan text not null default 'free' check(plan in('free','professional','business')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.skill_definitions(id text primary key,title text not null,description text not null default '',domain text not null default 'general',sort_order int not null default 0);
create table public.student_skills(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,skill_id text not null references public.skill_definitions(id) on delete cascade,level text not null check(level in('NOT STARTED','FOUNDATIONAL','OPERATIONAL','COMPETENT','ADVANCED','VERIFIED')),verified_at timestamptz,last_practiced_at timestamptz,evidence_count int not null default 0 check(evidence_count>=0),unique(user_id,skill_id));
create table public.learning_paths(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,goal text not null,level_ids int[] not null default '{}',status text not null default 'active' check(status in('active','completed','paused')),created_at timestamptz not null default now());
create table public.courses(id int primary key,title text not null,slug text not null unique,outcome text not null,published boolean not null default true,plan text not null default 'free' check(plan in('free','professional','business')));
create table public.modules(id uuid primary key default gen_random_uuid(),course_id int not null references public.courses(id) on delete cascade,title text not null,sort_order int not null default 0);
create table public.lessons(id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,title text not null,content jsonb not null default '{}'::jsonb,sort_order int not null default 0,published boolean not null default true);
create table public.resources(id uuid primary key default gen_random_uuid(),lesson_id uuid references public.lessons(id) on delete cascade,source text not null,author text,url text not null,language text not null default 'es',level text not null default 'foundational',license_status text not null default 'link_only',last_checked_at timestamptz,available boolean not null default true);
create table public.exercises(id uuid primary key default gen_random_uuid(),lesson_id uuid not null references public.lessons(id) on delete cascade,title text not null,instructions text not null,rubric jsonb not null default '{}'::jsonb);
create table public.assessments(id uuid primary key default gen_random_uuid(),course_id int not null references public.courses(id) on delete cascade,title text not null,rubric jsonb not null default '{}'::jsonb,practical boolean not null default true);
create table public.assessment_attempts(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,assessment_id uuid not null references public.assessments(id) on delete cascade,submission jsonb not null default '{}'::jsonb,score numeric check(score between 0 and 100),status text not null default 'submitted' check(status in('draft','submitted','reviewed')),created_at timestamptz not null default now());
create table public.evidence(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,skill_id text references public.skill_definitions(id),course_id int references public.courses(id),kind text not null default 'artifact',description text not null,artifact_url text,verification_status text not null default 'PENDING' check(verification_status in('PENDING','VERIFIED','REJECTED')),verified_at timestamptz,created_at timestamptz not null default now());
create table public.credentials(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,title text not null,issuer text not null default 'KOWI',credential_type text not null default 'internal',evidence_id uuid references public.evidence(id),issued_at timestamptz,revoked_at timestamptz,external_url text);
create table public.portfolios(id uuid primary key default gen_random_uuid(),user_id uuid not null unique default auth.uid() references auth.users(id) on delete cascade,headline text not null default '',summary text not null default '',is_public boolean not null default false,updated_at timestamptz not null default now());
create table public.learning_events(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,event_type text not null,course_id int references public.courses(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table public.school_agents(agent_id text primary key,role text not null,permissions text[] not null default '{}',tools text[] not null default '{}',risk_level text not null check(risk_level in('low','medium','high')),budget jsonb not null default '{"max_calls_per_session":20}'::jsonb,status text not null check(status in('DRAFT','ACTIVE','PAUSED','REVOKED','TERMINATED')));
create table public.school_project_links(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,course_id int references public.courses(id),created_at timestamptz not null default now(),unique(user_id,project_id));

insert into public.skill_definitions(id,title,domain,sort_order) values
('digital','Competencia digital','digital',1),('ai','IA','ai',2),('llm','LLM','ai',3),('prompting','Prompting','ai',4),('agents','Agentes','ai',5),('programming','Programación','engineering',6),('apis','APIs','engineering',7),('data','Datos','data',8),('sql','SQL','data',9),('cloud','Cloud','engineering',10),('cybersecurity','Ciberseguridad','security',11),('business','Negocio','business',12),('operations','Operaciones','business',13),('leadership','Liderazgo','business',14),('languages','Idiomas','general',15) on conflict do nothing;
insert into public.courses(id,slug,title,outcome,plan) values
(0,'diagnostico','Diagnóstico y Skill Graph','Mapear habilidades con evidencia','free'),(1,'competencia-digital','Competencia digital','Trabajar digitalmente con criterio','free'),(2,'ia-cero','Inteligencia artificial desde cero','Comprender usos y límites','free'),(3,'ia-vida','IA para la vida cotidiana','Aplicar IA con verificación','free'),(4,'ia-trabajo','IA para el trabajo','Mejorar un proceso medible','free'),(5,'prompting','Prompting','Diseñar instrucciones evaluables','free'),(6,'ia-responsable','IA responsable y verificación','Verificar y proteger datos','free'),(7,'llm','Fundamentos de LLM','Comprender contexto y límites','free'),(8,'context-engineering','Context Engineering','Diseñar contexto trazable','professional'),(9,'agents','AI Agents','Diseñar agentes controlables','professional'),(10,'api-json-webhooks','APIs, JSON y Webhooks','Conectar sistemas','professional'),(11,'mcp-tools','MCP y herramientas','Diseñar tools con permisos','professional'),(12,'sql-data','SQL y datos','Consultar datos relacionales','professional'),(13,'supabase','Supabase','Construir datos con Auth y RLS','professional'),(14,'git-github','Git y GitHub','Colaborar con control de cambios','professional'),(15,'web-next','Web, TypeScript y Next.js','Construir una feature web','professional'),(16,'cloud-vercel','Cloud y Vercel','Desplegar y verificar','professional'),(17,'cyber-ai','Ciberseguridad de IA','Modelar amenazas','professional'),(18,'agent-security','Agent Security','Aplicar least privilege','professional'),(19,'multi-agent','Multi-Agent Systems','Coordinar agentes','professional'),(20,'crm-automation','CRM y automatización','Automatizar pipeline con control','professional'),(21,'ai-economics','AI Economics','Medir coste y valor','professional'),(22,'saas','SaaS y emprendimiento','Validar un producto','professional'),(23,'sales-ops-leadership','Ventas, operaciones y liderazgo','Liderar adopción medible','professional'),(24,'capstone','Capstone Project','Construir y defender un proyecto','professional') on conflict do nothing;
insert into public.modules(course_id,title,sort_order) select id,'Misión práctica',1 from public.courses on conflict do nothing;
insert into public.lessons(module_id,title,content,sort_order)
select m.id,'Study → Build → Test → Execute → Prove',jsonb_build_object('discover','Define el problema','learn','Aprende el concepto mínimo','try','Haz una prueba guiada','build','Construye un entregable','break','Introduce un fallo','fix','Diagnostica y corrige','execute','Obtén un resultado reproducible','explain','Explica decisiones','prove','Resuelve sin guía','evidence','Guarda evidencia verificable'),1 from public.modules m where not exists(select 1 from public.lessons l where l.module_id=m.id);

insert into public.resources(source,author,url,language,level,license_status,last_checked_at) values
('MDN Web Docs','Mozilla','https://developer.mozilla.org/','en','foundational','link_only','2026-10-03'),
('OWASP Top 10','OWASP Foundation','https://owasp.org/www-project-top-ten/','en','competent','link_only','2026-10-03'),
('Microsoft Learn','Microsoft','https://learn.microsoft.com/','es','foundational','link_only','2026-10-03'),
('AWS Skill Builder','Amazon Web Services','https://skillbuilder.aws/','en','foundational','link_only','2026-10-03'),
('Supabase Docs','Supabase','https://supabase.com/docs','en','competent','link_only','2026-10-03'),
('Vercel Docs','Vercel','https://vercel.com/docs','en','competent','link_only','2026-10-03');
insert into public.school_agents(agent_id,role,permissions,risk_level,status) values
('school-orchestrator','Education Orchestrator',array['route_learning','read_authorized_progress'],'medium','ACTIVE'),
('school-diagnostic','Diagnostic Agent',array['score_diagnostic','read_authorized_evidence'],'low','ACTIVE'),
('school-learning-architect','Learning Architect',array['build_learning_path','read_authorized_progress'],'low','ACTIVE'),
('school-tutor','Tutor Agent',array['explain','generate_examples'],'low','ACTIVE'),
('school-socratic','Socratic Tutor',array['ask_questions','coach_reasoning'],'low','ACTIVE'),
('school-resource-curator','Resource Curator',array['propose_resources'],'low','ACTIVE'),
('school-content','Content Agent',array['draft_content'],'medium','ACTIVE'),
('school-video','Video Curriculum Agent',array['draft_video_package'],'low','ACTIVE'),
('school-practice','Practice Agent',array['generate_practice'],'low','ACTIVE'),
('school-lab','Lab Agent',array['generate_isolated_lab'],'medium','ACTIVE'),
('school-project','Project Agent',array['draft_project'],'medium','ACTIVE'),
('school-code-mentor','Code Mentor',array['review_code','explain_code'],'medium','ACTIVE'),
('school-business-mentor','Business Mentor',array['business_case_feedback'],'low','ACTIVE'),
('school-security-mentor','Security Mentor',array['security_feedback'],'medium','ACTIVE'),
('school-evaluator','Evaluator',array['score_attempt'],'medium','ACTIVE'),
('school-evidence-verifier','Evidence Verifier',array['verify_evidence'],'high','ACTIVE'),
('school-portfolio','Portfolio Agent',array['compose_portfolio'],'low','ACTIVE'),
('school-career','Career Agent',array['map_skills_to_roles'],'low','ACTIVE'),
('school-quality','Quality Agent',array['audit_content'],'low','ACTIVE'),
('school-security','School Security Agent',array['audit_permissions','pause_agent'],'high','ACTIVE');

alter table public.school_profiles enable row level security;alter table public.skill_definitions enable row level security;alter table public.student_skills enable row level security;alter table public.learning_paths enable row level security;alter table public.courses enable row level security;alter table public.modules enable row level security;alter table public.lessons enable row level security;alter table public.resources enable row level security;alter table public.exercises enable row level security;alter table public.assessments enable row level security;alter table public.assessment_attempts enable row level security;alter table public.evidence enable row level security;alter table public.credentials enable row level security;alter table public.portfolios enable row level security;alter table public.learning_events enable row level security;alter table public.school_agents enable row level security;alter table public.school_project_links enable row level security;
revoke all on public.school_profiles,public.skill_definitions,public.student_skills,public.learning_paths,public.courses,public.modules,public.lessons,public.resources,public.exercises,public.assessments,public.assessment_attempts,public.evidence,public.credentials,public.portfolios,public.learning_events,public.school_agents,public.school_project_links from anon,authenticated;
grant select on public.skill_definitions,public.courses,public.modules,public.lessons,public.resources,public.exercises,public.assessments to anon,authenticated;
grant select,insert,update,delete on public.school_profiles,public.student_skills,public.learning_paths,public.assessment_attempts,public.evidence,public.portfolios,public.learning_events,public.school_project_links to authenticated;
grant select on public.credentials to authenticated;
create policy school_public_skills on public.skill_definitions for select to anon,authenticated using(true);create policy school_public_courses on public.courses for select to anon,authenticated using(published);create policy school_public_modules on public.modules for select to anon,authenticated using(true);create policy school_public_lessons on public.lessons for select to anon,authenticated using(published);create policy school_public_resources on public.resources for select to anon,authenticated using(available);create policy school_public_exercises on public.exercises for select to anon,authenticated using(true);create policy school_public_assessments on public.assessments for select to anon,authenticated using(true);
do $$ declare t text; begin foreach t in array array['school_profiles','student_skills','learning_paths','assessment_attempts','evidence','portfolios','learning_events','school_project_links'] loop execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid())=user_id)',t||'_select',t);execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid())=user_id)',t||'_insert',t);execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id)',t||'_update',t);execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid())=user_id)',t||'_delete',t);end loop;end $$;
create policy school_credentials_select on public.credentials for select to authenticated using((select auth.uid())=user_id);
create index student_skills_owner on public.student_skills(user_id,skill_id);create index learning_paths_owner on public.learning_paths(user_id,created_at desc);create index attempts_owner on public.assessment_attempts(user_id,created_at desc);create index evidence_owner on public.evidence(user_id,created_at desc);create index learning_events_owner on public.learning_events(user_id,created_at desc);
commit;